/**
 * `visual-review init`: writes a repository's config, its Git LFS rule and its GitHub Actions
 * workflows from the templates in this package's templates/ directory.
 *
 * The workflows are the templates with four placeholders filled in (`# __SETUP__` is a comment,
 * so a template is valid YAML): the default branch, the
 * package manager's setup and install steps, the command that runs this CLI, and this package's
 * version (the gate job runs exactly that published version with npx). A workflow init wrote
 * starts with GENERATED, so `--force` rewrites it and never a workflow someone wrote by hand.
 */

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { CONFIG_FILE, loadConfig } from "./config.mjs";

const PACKAGE = join(dirname(fileURLToPath(import.meta.url)), "../..");
export const GENERATED = "# Generated by visual-review init";

/** Per package manager: the steps that install Node and the dependencies, and how to run the CLI. */
const MANAGERS = {
    npm: { lock: "package-lock.json", cli: "npx visual-review", setup: setup("npm", "npm ci") },
    pnpm: {
        lock: "pnpm-lock.yaml",
        cli: "pnpm exec visual-review",
        setup: `- uses: pnpm/action-setup@v4\n\n${setup("pnpm", "pnpm install --frozen-lockfile")}`,
    },
    yarn: { lock: "yarn.lock", cli: "yarn visual-review", setup: setup("yarn", "yarn install --frozen-lockfile") },
};

function setup(cache, install) {
    return [
        "- uses: actions/setup-node@v4",
        "  with:",
        "      node-version: 22.x",
        `      cache: ${cache}`,
        "",
        "# HUSKY=0: git hooks are for people, not for CI's install.",
        "- name: Install dependencies",
        `  run: ${install}`,
        "  env:",
        '      HUSKY: "0"',
    ].join("\n");
}

/**
 * The package manager a repository uses, from its lockfile.
 * @param {string} root the repository
 * @returns {"npm" | "pnpm" | "yarn"} the manager
 */
export function packageManager(root) {
    const found = Object.keys(MANAGERS).find((m) => m !== "npm" && existsSync(join(root, MANAGERS[m].lock)));
    return /** @type {"npm" | "pnpm" | "yarn"} */ (found ?? "npm");
}

/**
 * Fills in a template.
 * @param {string} name the template's file name in templates/
 * @param {{ branch: string, manager: "npm" | "pnpm" | "yarn", version: string }} values what goes in
 * @returns {string} the workflow
 */
export function renderTemplate(name, { branch, manager, version }) {
    const m = MANAGERS[manager];
    return readFileSync(join(PACKAGE, "templates", name), "utf8").replace(
        /^( *)# __SETUP__$|__BRANCH__|__CLI__|__VERSION__/gm,
        (match, indent) =>
            indent !== undefined
                ? m.setup
                      .split("\n")
                      .map((l) => (l === "" ? "" : indent + l))
                      .join("\n")
                : { __BRANCH__: branch, __CLI__: m.cli, __VERSION__: version }[match],
    );
}

function defaultBranch(root) {
    const git = (...args) => execFileSync("git", args, { cwd: root, encoding: "utf8", stdio: "pipe" }).trim();
    try {
        return git("symbolic-ref", "--short", "refs/remotes/origin/HEAD").replace(/^origin\//, "");
    } catch {
        try {
            return git("branch", "--show-current") || "main";
        } catch {
            return "main";
        }
    }
}

/**
 * Appends a line to a file unless a line already starts with `prefix`.
 * @param {string} file the file, created when missing
 * @param {string} prefix what an existing line starts with when the text is already there
 * @param {string} text the lines to append
 * @returns {boolean} whether it wrote
 */
function appendOnce(file, prefix, text) {
    const old = existsSync(file) ? readFileSync(file, "utf8") : "";
    if (old.split("\n").some((l) => l.startsWith(prefix))) {
        return false;
    }
    writeFileSync(file, `${old}${old === "" || old.endsWith("\n") ? "" : "\n"}${text}\n`);
    return true;
}

/**
 * Whether git already ignores a directory (asked of a file in it, since a rule such as `dir/*`
 * ignores the files but not the path itself).
 * @param {string} root the repository
 * @param {string} dir the directory, relative to the repository
 * @returns {boolean} true when a file in it is ignored
 */
function ignored(root, dir) {
    try {
        execFileSync("git", ["check-ignore", "-q", "--no-index", `${dir}/x`], { cwd: root, stdio: "ignore" });
        return true;
    } catch {
        return false;
    }
}

/**
 * Sets up a repository.
 * @param {string} root the repository's top level
 * @param {{ force?: boolean }} [options] rewrite the workflows init wrote before (never the
 *     config, which is the repository's own, and never a workflow written by hand)
 * @returns {string[]} one line per file: what was written or kept
 */
export function init(root, { force = false } = {}) {
    const report = [];
    const manager = packageManager(root);
    const configFile = join(root, CONFIG_FILE);
    if (existsSync(configFile)) {
        report.push(`kept     ${CONFIG_FILE}`);
    } else {
        const starter = {
            defaultBranch: defaultBranch(root),
            workflow: "visual-review.yml",
            baselines: "visual-baselines",
            workDir: ".visual-review",
            commitPrefix: "test",
            issueLabels: ["bug"],
            projects: {
                storybook: {
                    storybook: "storybook-static",
                    build: `${manager} run build-storybook`,
                    workers: 4,
                },
            },
        };
        writeFileSync(configFile, `${JSON.stringify(starter, null, 4)}\n`);
        report.push(`wrote    ${CONFIG_FILE}`);
    }
    const config = loadConfig(root);

    const rule = `${config.baselines}/**/*.png`;
    report.push(
        appendOnce(
            join(root, ".gitattributes"),
            `${rule} `,
            `# Visual review baselines are stored in Git LFS.\n${rule} filter=lfs diff=lfs merge=lfs -text`,
        )
            ? `wrote    .gitattributes (${rule} in Git LFS)`
            : "kept     .gitattributes",
    );
    report.push(
        !ignored(root, config.workDir) &&
            appendOnce(join(root, ".gitignore"), `/${config.workDir}/`, `/${config.workDir}/`)
            ? `wrote    .gitignore (/${config.workDir}/)`
            : "kept     .gitignore",
    );

    const version = JSON.parse(readFileSync(join(PACKAGE, "package.json"), "utf8")).version;
    const values = { branch: config.defaultBranch, manager, version };
    for (const [template, file] of [
        ["visual-review.yml", config.workflow],
        ["visual-seed.yml", "visual-seed.yml"],
    ]) {
        const path = join(root, ".github/workflows", file);
        const rel = `.github/workflows/${file}`;
        if (existsSync(path) && !(force && readFileSync(path, "utf8").startsWith(GENERATED))) {
            report.push(`kept     ${rel}${force ? " (not written by init, so never replaced)" : ""}`);
            continue;
        }
        mkdirSync(dirname(path), { recursive: true });
        writeFileSync(path, renderTemplate(template, values));
        report.push(`wrote    ${rel}`);
    }
    report.push(
        "",
        `Next: edit ${CONFIG_FILE} (one entry per Storybook), commit these files, and push a pull request.`,
        'Then make the "Visual gate" check required, and seed the first baselines (README, "Seeding").',
    );
    return report;
}
