/**
 * The format conformance suite: every fixture of every manifest under fixtures/ against its
 * expected result, and the import -> export -> import round trip for the formats graph-io writes.
 *
 * A fixture marked `knownFailure` (or `roundTripFailure`) runs as an expected failure: the suite
 * stays green while graph-io misses the expectation and turns red the moment a fix lands without
 * the marker being removed.
 *
 * `CONFORMANCE_REPORT=1 pnpm exec vitest run test/conformance` also writes REPORT.md next to this
 * file: per format, the fixture count, how many conform, and the known failures grouped by cause.
 */

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { afterAll, describe, expect, it } from "vitest";

import { checkFixture, checkRoundTrip, type Fixture, loadManifests, roundTrips } from "./harness.js";

interface Row {
    readonly format: string;
    readonly fixture: Fixture;
    readonly problems: readonly string[];
    readonly roundTrip: readonly string[] | null;
}

const rows = new Map<string, Row>();

const record = (format: string, fixture: Fixture, patch: Partial<Row>): void => {
    const key = `${format}/${fixture.file}`;
    const row = rows.get(key) ?? { format, fixture, problems: [], roundTrip: null };
    rows.set(key, { ...row, ...patch });
};

for (const manifest of loadManifests()) {
    const { format } = manifest;
    describe(`conformance: ${format}`, () => {
        for (const fixture of manifest.fixtures) {
            const test = fixture.knownFailure === undefined ? it : it.fails;
            test(fixture.file, async () => {
                const problems = await checkFixture(format, fixture);
                record(format, fixture, { problems });
                expect(problems).toEqual([]);
            });
        }
    });
    describe(`round trip: ${format}`, () => {
        for (const fixture of manifest.fixtures.filter((f) => roundTrips(format, f))) {
            const test = fixture.roundTripFailure === undefined ? it : it.fails;
            test(fixture.file, async () => {
                const problems = await checkRoundTrip(format, fixture);
                record(format, fixture, { roundTrip: problems });
                expect(problems).toEqual([]);
            });
        }
    });
}

afterAll(() => {
    if (process.env.CONFORMANCE_REPORT === undefined || rows.size === 0) {
        return;
    }
    writeFileSync(join(dirname(fileURLToPath(import.meta.url)), "REPORT.md"), renderReport([...rows.values()]));
});

/**
 * The markdown report.
 * @param all - every recorded row
 * @returns the document
 */
function renderReport(all: readonly Row[]): string {
    const out: string[] = [
        "<!-- THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT graph-io/test/conformance/",
        "     (the manifests under fixtures/ and conformance.test.ts) and rerun",
        "     CONFORMANCE_REPORT=1 pnpm exec vitest run test/conformance -->",
        "",
        "# graph-io conformance report",
        "",
        "Every fixture is imported as bytes and compared with an expectation taken from an independent",
        "reader or the format's specification. A known failure is a case where graph-io does not meet",
        "the expectation today; the reference points into",
        "`sources.md` next to this report (the research notes behind this corpus).",
        "",
        "| Format | Fixtures | Conform | Known failures | Round trips | Round-trip failures |",
        "|---|---|---|---|---|---|",
    ];
    const formats = [...new Set(all.map((r) => r.format))].sort();
    for (const format of formats) {
        const mine = all.filter((r) => r.format === format);
        const known = mine.filter((r) => r.fixture.knownFailure !== undefined).length;
        const trips = mine.filter((r) => r.roundTrip !== null);
        const tripFails = trips.filter((r) => r.fixture.roundTripFailure !== undefined).length;
        out.push(`| ${format} | ${mine.length} | ${mine.length - known} | ${known} | ${trips.length} | ${tripFails} |`);
    }
    for (const format of formats) {
        const mine = all.filter((r) => r.format === format);
        out.push("", `## ${format}`, "");
        const causes = new Map<string, Row[]>();
        for (const row of mine) {
            for (const cause of [row.fixture.knownFailure, row.fixture.roundTripFailure]) {
                if (cause !== undefined) {
                    const prefix = cause === row.fixture.knownFailure ? "" : "round trip: ";
                    causes.set(prefix + cause, [...(causes.get(prefix + cause) ?? []), row]);
                }
            }
        }
        if (causes.size === 0) {
            out.push("No known failures.");
            continue;
        }
        const sorted = [...causes.entries()].sort((a, b) => b[1].length - a[1].length || a[0].localeCompare(b[0]));
        for (const [cause, list] of sorted) {
            out.push(`### ${cause} (${list.length})`, "");
            for (const row of list) {
                const detail = cause.startsWith("round trip: ") ? (row.roundTrip ?? []) : row.problems;
                out.push(
                    `- \`${row.fixture.file}\`: ${detail.slice(0, 2).join("; ").replace(/\|/g, "\\|") || "(no detail)"}`,
                );
            }
            out.push("");
        }
    }
    return `${out.join("\n").trimEnd()}\n`;
}
