/**
 * The schema layer of the conformance suite: every GraphML, GEXF (1.3 and 1.2) and JGF text
 * graph-io exports -- a seeded sample of generated graphs and every conformance fixture that
 * imports -- is validated against the format's official schema (schemas/, unmodified copies) by
 * tools/validate_exports.py, which needs Python with lxml and jsonschema. DOT has no schema: when
 * Graphviz's gvpr is on the PATH, the reference parser must read every DOT export.
 *
 * An error is either a DEVIATION (the schema itself, or the validator, disagrees with the
 * specification's own examples and every mainstream reader; graph-io follows the examples) or a
 * KNOWN FAILURE (graph-io writes something the specification does not allow). Anything else fails
 * the suite. A known failure runs as an expected failure, so a fix turns it red until the entry
 * is removed.
 */

import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { type GraphSnapshot } from "@graphty/graph-format";
import fc from "fast-check";

import { importGraph } from "../../src/registry.js";
import { buildSnapshot, exporterOf, graphArb } from "./generative.js";
import { loadManifests } from "./harness.js";

const HERE = dirname(fileURLToPath(import.meta.url));

/** The exports that have an official schema: format, options, file suffix. */
const SCHEMA_EXPORTS = [
    { format: "graphml", options: { sanitizeIds: "mangle" }, suffix: "graphml" },
    { format: "gexf", options: {}, suffix: "gexf" },
    { format: "gexf", options: { version: "1.2" }, suffix: "gexf" },
    { format: "json", options: { dialect: "jgf" }, suffix: "jgf.json" },
    { format: "dot", options: {}, suffix: "gv" },
] as const;

/** How many generated graphs are exported per schema target. */
const GENERATED_SAMPLES = 250;

/** A class of schema error: which validator messages it covers and why. */
interface SchemaClass {
    readonly name: string;
    readonly kind: "graphml" | "gexf" | "jgf" | "dot";
    readonly pattern: RegExp;
    readonly reason: string;
}

/** Errors that are the schema's or the validator's, not graph-io's (each checked against the spec's own examples). */
export const SCHEMA_DEVIATIONS: readonly SchemaClass[] = [
    {
        name: "GEXF viz namespace",
        kind: "gexf",
        pattern: /viz\}(color|position|size|shape|thickness)': This element is not expected/,
        reason: "the XSDs are generated by trang from the normative RNC, whose `default namespace = inherit` puts color / position / size / shape in the GEXF namespace; the gexf.net samples, the primer, Gephi and networkx all write them in the viz namespace, and so does graph-io",
    },
    {
        name: "GraphML nested-graph keyref",
        kind: "graphml",
        // only in a document with a nested graph (checked in classify())
        pattern: /More than one match found for key-sequence/,
        reason: "node_id_key selects .//node in EVERY graph, so a nested graph's keys reach its parent's table twice and libxml2 rejects an outer edge into a nested graph; the GraphML primer's own nested.graphml fails identically",
    },
    {
        name: "NMTOKEN character edition",
        kind: "graphml",
        // only when the rejected value IS a fifth-edition Nmtoken (checked in classify())
        pattern: /'([^']*)' is not a valid value of the atomic type 'xs:NMTOKEN'/,
        reason: "libxml2 checks xs:NMTOKEN with the XML 1.0 second-edition character classes (XSD 1.0); graph-io's NMTOKEN test uses the XML 1.0 fifth-edition name characters (supplementary planes, U+FFFD...), which XSD 1.1 processors and every non-validating reader accept",
    },
    {
        name: "source text passed through",
        kind: "graphml",
        pattern: /attribute 'attr\.type': \[facet 'enumeration'\]/,
        reason: "an attr.type the source declared and GraphML does not define is written back as declared (the importer kept it as text with W_UNKNOWN_ATTR_TYPE); the source was already schema-invalid",
    },
    {
        name: "source date passed through",
        kind: "gexf",
        pattern: /attribute 'lastmodifieddate': '[^']*' is not a valid value of the atomic type 'xs:date'/,
        reason: "a meta lastmodifieddate the source wrote in another date syntax is written back as read; the source was already schema-invalid",
    },
];

/** Errors graph-io causes: open bugs. */
export const SCHEMA_KNOWN_FAILURES: readonly SchemaClass[] = [
    {
        name: "GEXF infinite weight spelling",
        kind: "gexf",
        pattern: /attribute 'weight': '-?Infinity' is not a valid value/,
        reason: "an infinite edge weight is written `Infinity`; the XSD types weight xs:float, whose spelling is INF / -INF (Gephi's Java parser reads Infinity, not INF, so the fix needs a decision)",
    },
    {
        name: "GraphML attr.name outside NMTOKEN",
        kind: "graphml",
        pattern: /attribute 'attr\.name': '[^']*' is not a valid value of the atomic type/,
        reason: "a column name is written as attr.name unchecked; a name with a space, or the `<name>#<id>` of graph-io's own rename rule, is not an NMTOKEN",
    },
    {
        name: "GEXF 1.3 date attribute type",
        kind: "gexf",
        pattern: /attribute 'type': \[facet 'enumeration'\] The value 'date(Time)?'/,
        reason: 'a date / dateTime column is declared with type="date" / "dateTime"; GEXF 1.3\'s attrtype-type has no such types (they are timeformat values), so the column should be written as string or its time value',
    },
    {
        name: "JGF numeric edge id",
        kind: "jgf",
        pattern: /edges\/\d+\/id: .* is not of type 'string'/,
        reason: "a numeric edge id is written as a JSON number; the JGF v2 schema requires a string",
    },
];

/** One document the validator rejected. */
interface InvalidDocument {
    readonly file: string;
    readonly kind: string;
    readonly errors: readonly string[];
    /** GraphML: whether a node holds a nested graph. */
    readonly nested?: boolean;
}

/** What the validator reported. */
export interface SchemaResult {
    readonly checked: Readonly<Record<string, number>>;
    readonly invalid: readonly InvalidDocument[];
}

/**
 * The Python interpreter to validate with: GRAPH_IO_SCHEMA_PYTHON, else python3 when it has
 * lxml and jsonschema.
 * @returns the interpreter, or null when none is available
 */
export function schemaPython(): string | null {
    const python = process.env.GRAPH_IO_SCHEMA_PYTHON ?? "python3";
    const probe = spawnSync(python, ["-c", "import lxml.etree, jsonschema"], { stdio: "ignore" });
    return probe.status === 0 ? python : null;
}

/**
 * Export the sample and the fixtures to a temporary directory and validate them.
 * @param python - the interpreter
 * @returns the validator's result
 */
export async function validateExports(python: string): Promise<SchemaResult> {
    const dir = mkdtempSync(join(tmpdir(), "graph-io-schemas-"));
    try {
        let n = 0;
        // Graphviz must read a generated graph's DOT with the same counts (a fixture's clusters are
        // container nodes in graph-io and subgraphs in Graphviz, so only its syntax is checked)
        const counts: Record<string, [number, number]> = {};
        const write = async (snapshot: GraphSnapshot, prefix: string): Promise<void> => {
            for (const target of SCHEMA_EXPORTS) {
                const file = `${prefix}-${n++}.${target.suffix}`;
                try {
                    const text = await exporterOf(target.format).exportToString(snapshot, target.options);
                    writeFileSync(join(dir, file), text);
                } catch {
                    // an export check() refuses is not a document; the round-trip layers cover it
                    continue;
                }
                if (target.format === "dot" && prefix === "generated") {
                    counts[file] = [snapshot.nodeCount, snapshot.edgeCount];
                }
            }
        };
        for (const g of fc.sample(graphArb, { numRuns: GENERATED_SAMPLES, seed: 20260923 })) {
            await write(buildSnapshot(g), "generated");
        }
        writeFileSync(join(dir, "expected-counts.json"), JSON.stringify(counts));
        for (const manifest of loadManifests()) {
            for (const fixture of manifest.fixtures) {
                if (fixture.expected.outcome !== "pass" || fixture.knownFailure !== undefined) {
                    continue;
                }
                const bytes = new Uint8Array(readFileSync(join(HERE, "fixtures", manifest.format, fixture.file)));
                const options = { format: manifest.format, filename: basename(fixture.file), ...fixture.options };
                const { snapshot } = await importGraph(bytes, options);
                await write(snapshot, `fixture-${manifest.format}`);
            }
        }
        const run = spawnSync(python, [join(HERE, "tools", "validate_exports.py"), dir], {
            encoding: "utf-8",
            maxBuffer: 64 * 1024 * 1024,
        });
        if (run.status !== 0) {
            throw new Error(`validate_exports.py failed: ${run.stderr.slice(0, 2000)}`);
        }
        return JSON.parse(run.stdout) as SchemaResult;
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
}

/** XML 1.0 fifth edition, production [7] Nmtoken (NameChar+), but for ZWNJ / ZWJ (see isNmtoken5th). */
const NMTOKEN_5TH =
    /^[-.0-9:A-Z_a-z\u00B7\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u037D\u037F-\u1FFF\u203F\u2040\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD\u{10000}-\u{EFFFF}]+$/u;

/**
 * Whether a text is an XML 1.0 fifth-edition Nmtoken.
 * @param text - the text
 * @returns true when it is
 */
function isNmtoken5th(text: string): boolean {
    // U+200C / U+200D are name characters too; a character class may not hold a joiner
    return NMTOKEN_5TH.test(text.replace(/\u200C|\u200D/gu, "_"));
}

/** libxml2's identity-constraint messages that only repeat an invalid id reported on its own. */
const FOLLOW_UP = /No precomputed value available|Not all fields of key identity-constraint/;

/**
 * The class of one error message.
 * @param doc - the document the validator rejected
 * @param message - one of its messages
 * @returns the deviation or known failure it belongs to, or null when unexplained
 */
function classify(doc: InvalidDocument, message: string): SchemaClass | null {
    const family = doc.kind.startsWith("gexf") ? "gexf" : doc.kind;
    for (const c of [...SCHEMA_DEVIATIONS, ...SCHEMA_KNOWN_FAILURES]) {
        const match = c.kind === family ? c.pattern.exec(message) : null;
        if (
            match !== null &&
            (c.name !== "NMTOKEN character edition" || isNmtoken5th(match[1])) &&
            (c.name !== "GraphML nested-graph keyref" || doc.nested === true)
        ) {
            return c;
        }
    }
    return null;
}

/**
 * The classes of every error of one invalid document; null entries are unexplained errors.
 * @param doc - the document the validator rejected
 * @returns one entry per message that is not a follow-up of another
 */
export function classifyDocument(doc: InvalidDocument): { message: string; cls: SchemaClass | null }[] {
    const { errors } = doc;
    return errors
        .filter((message) => !(FOLLOW_UP.test(message) && errors.some((m) => !FOLLOW_UP.test(m))))
        .map((message) => ({ message, cls: classify(doc, message) }));
}
