/**
 * Which counted-work test covers each graph-mutating public method (see `method-classes.ts`).
 *
 * A counted-work test runs the method and asserts how much work it did -- a count of visits,
 * searches, repaints or rebuilds, never a time -- so that a cost per call that grows with the size
 * of the graph fails it. New ones use `assertScalesLinearly` from `test/helpers/cost.ts`. Each
 * file named here must be a gating test (`*.test.ts`, not `*.bench.test.ts`).
 *
 * Registration is a static table rather than a call inside each test so that `cost-coverage.test.ts`
 * can read it in the default project without running the browser tests it names.
 */

/** Method (`Owner.method`, as `method-classes.ts` spells it) to the test files that count its work. */
export const COUNTED_WORK_TESTS: Readonly<Record<string, readonly string[]>> = {
    "DataManager.removeEdge": ["test/data/graph-store.test.ts"],
    "Graph.addEdge": ["test/browser/load-scaling.test.ts"],
    "Graph.setData": ["test/browser/load-scaling.test.ts"],
    "GraphSession.undo": ["test/session/history/scale.test.ts"],
    "LayoutEngine.removeEdge": ["test/layout/engine-removal.test.ts"],
    "LayoutEngine.removeNode": ["test/layout/engine-removal.test.ts"],
    "NotesApi.add": ["test/session/notes/write.test.ts"],
    "NotesApi.mergeDocument": ["test/session/mutation-scaling.test.ts"],
    "NotesApi.remove": ["test/session/notes/scaling.test.ts"],
    "NotesApi.update": ["test/session/notes/scaling.test.ts"],
    "RunsApi.start": ["test/session/results/lazy-ranking.test.ts", "test/session/results/column-median.test.ts"],
    "ScopeApi.remove": ["test/session/mutation-scaling.test.ts"],
    "ScopeApi.save": ["test/session/mutation-scaling.test.ts"],
    "SelectionApi.apply": ["test/session/mutation-scaling.test.ts"],
    "SelectionApi.clear": ["test/session/mutation-scaling.test.ts"],
    "SelectionApi.promote": ["test/session/mutation-scaling.test.ts"],
    "SessionConfig.set": ["test/session/mutation-scaling.test.ts"],
    "SessionDataApi.addEdges": ["test/session/history/graph-paint.test.ts"],
    "SessionDataApi.addNodes": ["test/session/history/graph-paint.test.ts"],
    "SessionDataApi.clear": ["test/browser/bulk-teardown.test.ts"],
    "SessionDataApi.declare": ["test/session/mutation-scaling.test.ts"],
    "SessionDataApi.removeEdges": ["test/session/mutation-scaling.test.ts"],
    "SessionDataApi.removeNodes": ["test/browser/bulk-teardown.test.ts"],
    "SessionDataApi.updateEdges": ["test/session/mutation-scaling.test.ts"],
    "SessionDataApi.updateNodes": ["test/session/mutation-scaling.test.ts"],
    "SetsApi.addMembers": ["test/session/mutation-scaling.test.ts"],
    "SetsApi.combine": ["test/session/mutation-scaling.test.ts"],
    "SetsApi.create": ["test/session/mutation-scaling.test.ts"],
    "SetsApi.createFrom": ["test/session/mutation-scaling.test.ts"],
    "SetsApi.createPath": ["test/session/mutation-scaling.test.ts"],
    "SetsApi.redefine": ["test/session/mutation-scaling.test.ts"],
    "SetsApi.remove": ["test/session/mutation-scaling.test.ts"],
    "SetsApi.removeMembers": ["test/session/mutation-scaling.test.ts"],
    "SetsApi.rename": ["test/session/mutation-scaling.test.ts"],
    "SetsApi.restore": ["test/session/mutation-scaling.test.ts"],
    "StylesApi.add": ["test/session/mutation-scaling.test.ts"],
    "StylesApi.applyTemplate": ["test/session/mutation-scaling.test.ts"],
    "StylesApi.encode": ["test/session/mutation-scaling.test.ts"],
    "StylesApi.move": ["test/session/mutation-scaling.test.ts"],
    "StylesApi.remove": ["test/session/mutation-scaling.test.ts"],
    "StylesApi.removeBySource": ["test/session/mutation-scaling.test.ts"],
    "StylesApi.resolveToStatic": ["test/session/mutation-scaling.test.ts"],
    "StylesApi.setValueHidden": ["test/session/mutation-scaling.test.ts"],
    "StylesApi.update": ["test/session/mutation-scaling.test.ts"],
    "VisibilityApi.set": ["test/session/mutation-scaling.test.ts"],
    "VisibilityApi.setWindow": ["test/session/mutation-scaling.test.ts"],
};

/** The GitHub issue tracking the methods below. */
export const NOT_YET_COVERED_ISSUE = 1643;

/**
 * Mutating methods with no counted-work test yet (issue #1643). This list only shrinks: write the
 * test, register it above, and delete the method here. `cost-coverage.test.ts` fails on a method
 * that is both here and registered, and on one that is no longer a mutating method in the reports.
 */
export const NOT_YET_COVERED: readonly string[] = [
    "AiController.execute",
    "AiManager.execute",
    "AiManager.retry",
    "Algorithm.publishResult",
    "Algorithm.run",
    "AlgorithmManager.dispose",
    "AlgorithmManager.init",
    "AlgorithmManager.runAlgorithm",
    "AlgorithmManager.runAlgorithmsFromTemplate",
    "DataManager.addDataFromSource",
    "DataManager.addEdge",
    "DataManager.addEdges",
    "DataManager.addNode",
    "DataManager.addNodes",
    "DataManager.bindSession",
    "DataManager.clear",
    "DataManager.dispose",
    "DataManager.init",
    "DataManager.reconcile",
    "DataManager.removeNodeAndIncidentEdges",
    "DataManager.setEdges",
    "DataManager.setGraphContext",
    "DataManager.setLayoutEngine",
    "DataManager.setNodes",
    "DataManager.startLabelAnimations",
    "DataManager.updateStyles",
    "DeclaredAlgorithm.publishResult",
    "DeclaredAlgorithm.run",
    "Edge.applySessionPaint",
    "Edge.dispose",
    "Edge.invalidatePositionCache",
    "Edge.setRenderVisible",
    "Edge.setSelected",
    "Edge.transformArrowCap",
    "Edge.transformEdgeMesh",
    "Edge.update",
    "Edge.updateRays",
    "Edge.updateStyle",
    "Graph.addDataFromSource",
    "Graph.addEdges",
    "Graph.addNode",
    "Graph.addNodes",
    "Graph.aiCommand",
    "Graph.applySuggestedStyles",
    "Graph.batchOperations",
    "Graph.clearData",
    "Graph.deselectNode",
    "Graph.dispose",
    "Graph.importCameraPresets",
    "Graph.init",
    "Graph.loadFromFile",
    "Graph.loadFromUrl",
    "Graph.removeCameraPreset",
    "Graph.removeEdges",
    "Graph.removeNodes",
    "Graph.render",
    "Graph.retryLastAiCommand",
    "Graph.run",
    "Graph.runAlgorithm",
    "Graph.runAlgorithmsFromTemplate",
    "Graph.saveCameraPreset",
    "Graph.select",
    "Graph.selectNode",
    "Graph.setBackground",
    "Graph.setEdges",
    "Graph.setLayout",
    "Graph.setLayoutBehavior",
    "Graph.setLayoutScope",
    "Graph.setNodes",
    "Graph.setSelectionStyle",
    "Graph.setViewMode",
    "Graph.shutdown",
    "Graph.update",
    "Graph.updateEdges",
    "Graph.updateNodes",
    "GraphCommand.execute",
    "GraphSession.dispose",
    "GraphSession.execute",
    "GraphSession.redo",
    "GraphSession.run",
    "Graphty.addDataFromSource",
    "Graphty.addEdge",
    "Graphty.addEdges",
    "Graphty.addNode",
    "Graphty.addNodes",
    "Graphty.aiCommand",
    "Graphty.applySuggestedStyles",
    "Graphty.asyncFirstUpdated",
    "Graphty.batchOperations",
    "Graphty.clearData",
    "Graphty.connectedCallback",
    "Graphty.deselectNode",
    "Graphty.disconnectedCallback",
    "Graphty.firstUpdated",
    "Graphty.importCameraPresets",
    "Graphty.loadFromFile",
    "Graphty.loadFromUrl",
    "Graphty.pin",
    "Graphty.removeCameraPreset",
    "Graphty.removeEdges",
    "Graphty.removeNodes",
    "Graphty.render",
    "Graphty.retryLastAiCommand",
    "Graphty.run",
    "Graphty.runAlgorithm",
    "Graphty.saveCameraPreset",
    "Graphty.select",
    "Graphty.selectNode",
    "Graphty.setData",
    "Graphty.setLayout",
    "Graphty.setViewMode",
    "Graphty.shutdown",
    "Graphty.unpin",
    "Graphty.updateEdges",
    "Graphty.updateNodes",
    "LayoutEngine.addEdge",
    "LayoutEngine.addEdges",
    "LayoutEngine.addNode",
    "LayoutEngine.addNodes",
    "LayoutEngine.attachPositions",
    "LayoutEngine.dispose",
    "LayoutEngine.init",
    "LayoutEngine.loadArrangement",
    "LayoutEngine.pin",
    "LayoutEngine.publishPositions",
    "LayoutEngine.setHoldMask",
    "LayoutEngine.setNodePosition",
    "LayoutEngine.step",
    "LayoutEngine.unpin",
    "LayoutEngine.updatePositions",
    "LayoutEngine.writeNodePosition",
    "LayoutManager.dispose",
    "LayoutManager.init",
    "LayoutManager.loadArrangement",
    "LayoutManager.setGraphContext",
    "LayoutManager.step",
    "LayoutManager.stepBatch",
    "LayoutManager.updatePositions",
    "LayoutManager.updateStyles",
    "LoadDraft.load",
    "Manager.dispose",
    "Manager.init",
    "Node.applySessionPaint",
    "Node.dispose",
    "Node.pin",
    "Node.refreshSelectionOverlay",
    "Node.setRenderState",
    "Node.setSelected",
    "Node.unpin",
    "Node.update",
    "Node.updateStyle",
    "ProjectApi.open",
    "ProjectApi.rename",
    "RenderManager.dispose",
    "RenderManager.init",
    "Run.rerun",
    "RunsApi.batch",
    "RunsApi.remove",
    "SelectionManager.bindSelection",
    "SelectionManager.deselect",
    "SelectionManager.dispose",
    "SelectionManager.init",
    "SelectionManager.onEdgesRemoved",
    "SelectionManager.onNodeRemoved",
    "SelectionManager.select",
    "SelectionManager.selectById",
    "SelectionManager.setDataManager",
    "SessionDataApi.import",
    "SessionDataApi.renameSource",
    "SessionHistory.clear",
    "SessionHistory.restoreTo",
    "SessionLayout.set",
    "SessionLayout.setDimension",
    "SessionPositions.pin",
    "SessionPositions.set",
    "SessionPositions.unpin",
    "SessionViews.remove",
    "SessionViews.save",
    "StylesApi.highlight",
    "UpdateManager.bindViewMasks",
    "UpdateManager.dispose",
    "UpdateManager.forceEdgeWalk",
    "UpdateManager.init",
    "UpdateManager.invalidateViewMasks",
    "UpdateManager.meshesAdded",
    "UpdateManager.rebindScene",
    "UpdateManager.redrawArrangement",
    "UpdateManager.renderFrames",
    "UpdateManager.stepFrames",
    "UpdateManager.syncStyles",
    "UpdateManager.syncViewMasks",
    "UpdateManager.update",
    "UpdateManager.updateConfig",
];
