export enum ScreenshotErrorCode {
    ENGINE_NOT_CONFIGURED = "ENGINE_NOT_CONFIGURED",
    PRESERVING_BUFFER_REQUIRED = "PRESERVING_BUFFER_REQUIRED",
    DIMENSION_TOO_LARGE = "DIMENSION_TOO_LARGE",
    INVALID_DIMENSIONS = "INVALID_DIMENSIONS",
    ASPECT_RATIO_MISMATCH = "ASPECT_RATIO_MISMATCH",
    OUT_OF_MEMORY = "OUT_OF_MEMORY",
    CANVAS_ALLOCATION_FAILED = "CANVAS_ALLOCATION_FAILED",
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT",
    WEBP_NOT_SUPPORTED = "WEBP_NOT_SUPPORTED",
    TRANSPARENT_REQUIRES_PNG = "TRANSPARENT_REQUIRES_PNG",
    CLIPBOARD_NOT_SUPPORTED = "CLIPBOARD_NOT_SUPPORTED",
    CLIPBOARD_PERMISSION_DENIED = "CLIPBOARD_PERMISSION_DENIED",
    CLIPBOARD_NOT_SECURE_CONTEXT = "CLIPBOARD_NOT_SECURE_CONTEXT",
    CLIPBOARD_WRITE_FAILED = "CLIPBOARD_WRITE_FAILED",
    CAMERA_PRESET_NOT_FOUND = "CAMERA_PRESET_NOT_FOUND",
    CAMERA_PRESET_NOT_AVAILABLE_IN_2D = "CAMERA_PRESET_NOT_AVAILABLE_IN_2D",
    CAMERA_TYPE_NOT_SUPPORTED = "CAMERA_TYPE_NOT_SUPPORTED",
    LAYOUT_SETTLE_TIMEOUT = "LAYOUT_SETTLE_TIMEOUT",
    SCREENSHOT_CAPTURE_FAILED = "SCREENSHOT_CAPTURE_FAILED",
    PRESET_NOT_FOUND = "PRESET_NOT_FOUND",
    RESOLUTION_TOO_HIGH = "RESOLUTION_TOO_HIGH",
}

export class ScreenshotError extends Error {
    constructor(
        message: string,
        public code: ScreenshotErrorCode,
        public details?: unknown,
    ) {
        super(message);
        this.name = "ScreenshotError";
        Object.setPrototypeOf(this, ScreenshotError.prototype);
    }
}
