/**
 * Writes the two tier 1 samples that exist only as bundled graph-samples modules, Les Miserables
 * and Florentine families, into public/samples/ as GML with graph-io's GML writer, so the start
 * screen opens them by URL through graphty-element's ordinary import like any other file
 * (design/ui/tier1-real-app/plan.md section 1, "Samples").
 *
 * Each node gets a `name` attribute with its readable name ("Mlle Baptistine" for the id
 * "MlleBaptistine"). The Les Miserables edge value is written under `shared_chapters`, which says
 * what it counts, rather than GML's default `value`.
 *
 * Run: npm run samples:write (from graphty/). Rerun after graph-samples changes a dataset.
 */

import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { fromEdgeArrays } from "@graphty/graph-format";
import { gmlExporter } from "@graphty/graph-io/gml";
import type { SampleGraph } from "@graphty/graph-samples";
import { florentineFamilies } from "@graphty/graph-samples/datasets/florentine-families";
import { lesMiserables } from "@graphty/graph-samples/datasets/les-miserables";

const OUT = resolve(dirname(fileURLToPath(import.meta.url)), "../public/samples");

/**
 * A readable name from a run-together id: "MlleBaptistine" -> "Mlle Baptistine",
 * "CountessDeLo" -> "Countess de Lo", "Woman1" -> "Woman 1".
 * @param id - the dataset's node id.
 * @returns the name.
 */
function readableName(id: string): string {
    return id.replaceAll(/([a-z])([A-Z0-9])/g, "$1 $2").replaceAll(" De ", " de ");
}

/**
 * Writes one sample.
 * @param file - the file name under public/samples/.
 * @param graph - the dataset.
 * @param weightKey - the edge key the weights are written under, for a weighted dataset.
 */
async function write(file: string, graph: SampleGraph, weightKey?: string): Promise<void> {
    const ids = graph.ids ?? [];
    const snapshot = fromEdgeArrays({
        ...graph,
        nodeColumns: { name: { data: ids.map(readableName), decl: { dtype: "string" } } },
    });
    // GML ids are integers: "mangle" numbers the nodes and keeps each original id in
    // graphty_originalId, which the importer restores.
    const text = await gmlExporter.exportToString(snapshot, { sanitizeIds: "mangle", weightKey });
    const warning =
        "# THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT graphty/scripts/write-sample-gml.ts\n";
    writeFileSync(resolve(OUT, file), warning + text);
    console.log(`wrote ${file}: ${String(snapshot.nodeCount)} nodes, ${String(snapshot.edgeCount)} edges`);
}

await write("les-miserables.gml", lesMiserables(), "shared_chapters");
await write("florentine.gml", florentineFamilies());
