export default {
    extends: ["@commitlint/config-conventional"],
    rules: {
        "scope-enum": [
            2,
            "always",
            [
                "graph-format",
                "graph-io",
                "graph-samples",
                "webgpu-graph-algorithms",
                "algorithms",
                "layout",
                "graphty-element",
                "compact-mantine",
                "remote-logger",
                "graphty",
                "visual-review",
                "githerd",
                "gpu-3d-force-layout",
                "deps",
                "release",
                "ci",
                "docs",
                "tools",
                "workspace",
            ],
        ],
    },
};
