// THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE DIRECTLY
// This is the base ESLint configuration for the monorepo
// Package-specific configs should import and extend this

import eslint from '@eslint/js';
import stylistic from '@stylistic/eslint-plugin';
import simpleImportSort from 'eslint-plugin-simple-import-sort';
import tseslint from 'typescript-eslint';

// Shared stylistic rules
const stylisticRules = {
  '@stylistic/array-bracket-spacing': ['error', 'never'],
  '@stylistic/arrow-parens': ['error', 'always'],
  '@stylistic/arrow-spacing': 'error',
  '@stylistic/block-spacing': 'error',
  '@stylistic/brace-style': ['error', '1tbs'],
  '@stylistic/comma-dangle': ['error', 'always-multiline'],
  '@stylistic/comma-spacing': 'error',
  '@stylistic/computed-property-spacing': ['error', 'never'],
  '@stylistic/indent': ['error', 2, { SwitchCase: 1 }],
  '@stylistic/key-spacing': 'error',
  '@stylistic/keyword-spacing': 'error',
  '@stylistic/linebreak-style': ['error', 'unix'],
  '@stylistic/max-len': ['error', { code: 120, ignoreUrls: true }],
  '@stylistic/member-delimiter-style': 'error',
  '@stylistic/no-extra-semi': 'error',
  '@stylistic/no-multi-spaces': 'error',
  '@stylistic/no-multiple-empty-lines': ['error', { max: 1 }],
  '@stylistic/no-trailing-spaces': 'error',
  '@stylistic/object-curly-spacing': ['error', 'always'],
  '@stylistic/quotes': ['error', 'single'],
  '@stylistic/semi': ['error', 'always'],
  '@stylistic/space-before-blocks': 'error',
  '@stylistic/space-before-function-paren': ['error', {
    anonymous: 'always',
    named: 'never',
    asyncArrow: 'always',
  }],
  '@stylistic/space-in-parens': ['error', 'never'],
  '@stylistic/space-infix-ops': 'error',
};

// Shared base rules
const baseRules = {
  'camelcase': 'error',
  'curly': 'error',
  'eqeqeq': ['error', 'always'],
  'no-console': 'warn',
  'no-var': 'error',
  'prefer-const': 'error',
  'simple-import-sort/imports': 'error',
  'simple-import-sort/exports': 'error',
};

// Export factory function for creating package configs
export function createEslintConfig(tsconfigPath = './tsconfig.json') {
  return tseslint.config(
    // Base JavaScript rules
    eslint.configs.recommended,

    // TypeScript strict rules for source files
    {
      files: ['src/**/*.ts', 'src/**/*.tsx'],
      extends: [
        ...tseslint.configs.strictTypeChecked,
        ...tseslint.configs.stylisticTypeChecked,
      ],
      languageOptions: {
        parserOptions: {
          projectService: true,
          tsconfigRootDir: import.meta.dirname,
        },
      },
      plugins: {
        '@stylistic': stylistic,
        'simple-import-sort': simpleImportSort,
      },
      rules: {
        ...stylisticRules,
        ...baseRules,
        '@typescript-eslint/no-explicit-any': 'error',
        '@typescript-eslint/explicit-function-return-type': ['error', {
          allowExpressions: true,
        }],
      },
    },

    // Relaxed rules for test files
    {
      files: ['**/*.spec.ts', '**/*.test.ts', 'test/**/*.ts'],
      extends: [
        ...tseslint.configs.recommended,
      ],
      languageOptions: {
        parserOptions: {
          projectService: true,
          tsconfigRootDir: import.meta.dirname,
        },
      },
      plugins: {
        '@stylistic': stylistic,
        'simple-import-sort': simpleImportSort,
      },
      rules: {
        ...stylisticRules,
        ...baseRules,
        '@typescript-eslint/no-explicit-any': 'off',
        '@typescript-eslint/explicit-function-return-type': 'off',
        'no-console': 'off',
      },
    },

    // Ignore patterns
    {
      ignores: [
        'dist/**',
        'node_modules/**',
        'coverage/**',
        '*.config.js',
        '*.config.ts',
      ],
    },
  );
}

// Default export for packages that just need standard config
export default createEslintConfig();
