packages:
    - "graph-format"
    - "graph-io"
    - "webgpu-graph-algorithms"
    - "graph-samples"
    - "algorithms"
    - "layout"
    - "graphty-element"
    - "graphty"
    - "remote-logger"
    - "compact-mantine"
