// THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE DIRECTLY
// This is the shared Vite configuration for the monorepo
// Package-specific configs should import and extend this

import { resolve } from "path";
import { defineConfig } from "vite";
import type { UserConfig } from "vite";

export interface ViteConfigOptions {
    packageName: string;
    packagePath: string;
    entry?: string;
    external?: string[];
    globals?: Record<string, string>;
}

export function createViteConfig(options: ViteConfigOptions): UserConfig {
    const { packageName, packagePath, entry = "src/index.ts", external = [], globals = {} } = options;

    return defineConfig({
        build: {
            lib: {
                entry: resolve(packagePath, entry),
                name: packageName,
                formats: ["es", "umd"],
                fileName: (format) => `${packageName}.${format === "es" ? "js" : "umd.js"}`,
            },
            rollupOptions: {
                external: [
                    "typedfastbitset",
                    "lit",
                    "@lit/reactive-element",
                    "@babylonjs/core",
                    "@babylonjs/gui",
                    "react",
                    "react-dom",
                    ...external,
                ],
                output: {
                    globals: {
                        typedfastbitset: "TypedFastBitSet",
                        lit: "Lit",
                        "@babylonjs/core": "BABYLON",
                        "@babylonjs/gui": "BABYLON.GUI",
                        react: "React",
                        "react-dom": "ReactDOM",
                        ...globals,
                    },
                },
            },
            sourcemap: true,
            target: "es2020",
            outDir: resolve(packagePath, "dist"),
        },
        // The dev-server port comes from the command line (`--port $PORT`), which servherd sets.
        server: {
            open: true,
        },
    });
}
