/**
 * The reference section of README.md (every layout, algorithm, generator, dataset and file format with its options),
 * generated from the source so it cannot drift: option names, types and descriptions come from the TypeScript types
 * and their doc comments (this package's and those of the graphty algorithms, layout and graph-samples packages), the
 * lists from what the package registers, and the defaults from the values it passes.
 *
 * test/reference.test.ts fails when README.md differs from what this produces; `npm run docs:reference` rewrites it.
 */

import { fileURLToPath } from "node:url";

import { DATASETS } from "@graphty/graph-samples";
import { format, resolveConfig } from "prettier";
import ts from "typescript";

import {
    ALGORITHM_NAMES,
    ASYNC_ALGORITHM_NAMES,
    DEFAULTS as ALGORITHM_DEFAULTS,
    DIRECTED as DIRECTED_ALGORITHMS,
} from "../src/algorithms.js";
import { DEFAULTS as LAYOUT_DEFAULTS, LAYOUT_NAMES, SIMULATION_DEFAULTS, SIMULATIONS } from "../src/layouts.js";
import { BUNDLED_DATASET_NAMES, GENERATORS } from "../src/samples.js";

/** The markers around the generated part of README.md. */
const BEGIN = "<!-- reference:begin (generated by scripts/reference.ts: run `npm run docs:reference`) -->";
const END = "<!-- reference:end -->";

const pkg = fileURLToPath(new URL("..", import.meta.url));

/** One option as the tables show it. */
interface Option {
    readonly name: string;
    readonly type: string;
    readonly required: boolean;
    readonly doc: string;
}

// Options this package sets itself, so a caller never passes them: the layout frame and stepping, and the library
// spellings the extension replaces with a selector-taking option of its own (bfs `start` is `root` here).
const SET_BY_EXTENSION = new Set([
    "scale",
    "center",
    "pos",
    "iterationsPerStep",
    "fixed",
    "start",
    "weights",
    "weighted",
]);
// Options of every algorithm, documented once.
const COMMON_ALGORITHM = ["directed", "weight", "field", "gpu"];
// Layout options with a Cytoscape-facing meaning of their own, documented per layout from GraphtyLayoutOptions.
const PER_LAYOUT_EXTENSION: Readonly<Record<string, readonly string[]>> = {
    shell: ["nlist"],
    multipartite: ["subsets"],
    bipartite: ["top"],
    bfs: ["root"],
    radial: ["root"],
};
// The @graphty/layout option type each simulation runs with (the static layouts read their function's parameter).
const SIMULATION_TYPES: Readonly<Record<string, string>> = {
    forceatlas2: "ForceAtlas2Options",
    "fruchterman-reingold": "FruchtermanReingoldOptions",
    "spring-electrical": "SpringElectricalOptions",
};

/**
 * Cleans a doc comment for a table cell: one line, no references to design documents (they are not published).
 * @param s - the doc text
 * @returns the cell text
 */
function cell(s: string): string {
    return s
        .replace(/\s*\((?:see )?design [^)]*\)/gi, "")
        .replace(/\{@link\s+([^}\s|]+)[^}]*\}/g, "`$1`")
        .replace(/\s+/g, " ")
        .replace(/\|/g, "\\|")
        .trim();
}

/**
 * The default a doc comment states ("default 0.85", "Default: every edge weighs 1"), or "" when it states none.
 * @param doc - the doc text
 * @returns the default as written
 */
function statedDefault(doc: string): string {
    const marked = /(\S+) \(default\)/.exec(doc);
    if (marked !== null) {
        return marked[1];
    }
    const m = /\bdefaults?(?: is| to)?:?\s+/i.exec(doc);
    if (m === null) {
        return "";
    }
    // up to the end of the clause: a semicolon, a full stop, or a closing bracket the clause did not open
    const rest = doc.slice(m.index + m[0].length);
    let depth = 0;
    for (let i = 0; i < rest.length; i++) {
        const ch = rest[i];
        if (ch === "(") {
            depth++;
        } else if (ch === ")") {
            if (depth === 0) {
                return rest.slice(0, i).trim();
            }
            depth--;
        } else if (depth === 0 && (ch === ";" || /^(?:\.(?:\s|$)|, | and )/.test(rest.slice(i)))) {
            return rest.slice(0, i).trim();
        }
    }
    return rest.trim();
}

/**
 * A default value as code.
 * @param v - the value
 * @returns `v` in backticks
 */
function code(v: unknown): string {
    return `\`${typeof v === "string" ? JSON.stringify(v) : String(v)}\``;
}

/**
 * A type in a table cell.
 * @param t - the type text
 * @returns the cell text
 */
function typeCell(t: string): string {
    return `\`${t.replace(/\|/g, "\\|")}\``;
}

/** The type checker over the package source. */
class Source {
    readonly checker: ts.TypeChecker;
    private readonly program: ts.Program;

    constructor() {
        const config = ts.getParsedCommandLineOfConfigFile(
            `${pkg}tsconfig.json`,
            {},
            {
                ...ts.sys,
                onUnRecoverableConfigFileDiagnostic: (d) => {
                    throw new Error(ts.flattenDiagnosticMessageText(d.messageText, "\n"));
                },
            },
        );
        if (config === undefined) {
            throw new Error("tsconfig.json could not be read");
        }
        this.program = ts.createProgram([`${pkg}src/index.ts`, `${pkg}src/samples.ts`], config.options);
        this.checker = this.program.getTypeChecker();
    }

    /**
     * The exports of a module, by name.
     * @param file - a source file of this package, relative to the package
     * @param from - a module specifier imported by that file, or undefined for the file itself
     * @returns the exported symbols
     */
    exportsOf(file: string, from?: string): Map<string, ts.Symbol> {
        const sf = this.program.getSourceFile(`${pkg}${file}`);
        if (sf === undefined) {
            throw new Error(`${file} is not in the program`);
        }
        let node: ts.Node = sf;
        if (from !== undefined) {
            const decl = sf.statements.find(
                (s): s is ts.ImportDeclaration =>
                    ts.isImportDeclaration(s) && (s.moduleSpecifier as ts.StringLiteral).text === from,
            );
            if (decl === undefined) {
                throw new Error(`${file} does not import ${from}`);
            }
            node = decl.moduleSpecifier;
        }
        const mod = this.checker.getSymbolAtLocation(node);
        if (mod === undefined) {
            throw new Error(`no module symbol for ${from ?? file}`);
        }
        return new Map(this.checker.getExportsOfModule(mod).map((s) => [s.name, s]));
    }

    /**
     * The declared type of an exported type alias or interface, or the type of an exported value.
     * @param sym - the symbol
     * @returns its type
     */
    typeOf(sym: ts.Symbol): ts.Type {
        const s = sym.flags & ts.SymbolFlags.Alias ? this.checker.getAliasedSymbol(sym) : sym;
        return s.flags & (ts.SymbolFlags.TypeAlias | ts.SymbolFlags.Interface)
            ? this.checker.getDeclaredTypeOfSymbol(s)
            : this.checker.getTypeOfSymbol(s);
    }

    /**
     * The options parameter of a function type.
     * @param fn - the function's type
     * @param index - the parameter's position
     * @returns the parameter's type without undefined, or undefined when there is no such parameter
     */
    param(fn: ts.Type, index: number): ts.Type | undefined {
        const sig = fn.getCallSignatures()[0];
        if (sig === undefined || sig.getParameters().length === 0) {
            return undefined;
        }
        const p = sig.getParameters()[Math.min(index, sig.getParameters().length - 1)];
        let t = this.checker.getTypeOfSymbol(p);
        // the algorithm methods take `...options`, a tuple of zero or one options object
        if (this.checker.isTupleType(t)) {
            t = this.checker.getTypeArguments(t as ts.TypeReference)[index];
        } else if (index >= sig.getParameters().length) {
            return undefined;
        }
        return t === undefined ? undefined : this.checker.getNonNullableType(t);
    }

    /**
     * The properties of an options type.
     * @param type - the options type
     * @returns one entry per property, in declaration order
     */
    options(type: ts.Type): Option[] {
        return this.checker
            .getPropertiesOfType(this.checker.getApparentType(type))
            .filter((p) => !p.name.startsWith("__"))
            .map((p) => {
                const t = this.checker.getNonNullableType(this.checker.getTypeOfSymbol(p));
                return {
                    name: p.name,
                    type: this.checker.typeToString(
                        t,
                        undefined,
                        ts.TypeFormatFlags.NoTruncation | ts.TypeFormatFlags.UseAliasDefinedOutsideCurrentScope,
                    ),
                    required: (p.flags & ts.SymbolFlags.Optional) === 0,
                    doc: ts.displayPartsToString(p.getDocumentationComment(this.checker)),
                };
            });
    }

    /**
     * The first sentence of a symbol's doc comment.
     * @param sym - the symbol
     * @returns the sentence, or ""
     */
    summary(sym: ts.Symbol): string {
        const s = sym.flags & ts.SymbolFlags.Alias ? this.checker.getAliasedSymbol(sym) : sym;
        const doc = ts.displayPartsToString(s.getDocumentationComment(this.checker));
        // the first full stop that ends a sentence: before a capital or the end, and not after an initial or "et al"
        const end = /(?<!\b[A-Z]|\bal|\.)\.(?=\s+[A-Z(]|\s*$)/.exec(doc);
        return end === null ? doc : doc.slice(0, end.index + 1);
    }
}

/**
 * An options table.
 * @param rows - the options
 * @param defaults - this package's own defaults, by option name
 * @returns the markdown lines
 */
function table(rows: readonly Option[], defaults: Readonly<Record<string, unknown>> = {}): string[] {
    const out = ["| Option | Type | Default | Meaning |", "| --- | --- | --- | --- |"];
    for (const o of rows) {
        let d = o.required ? "required" : cell(statedDefault(o.doc));
        if (Object.keys(defaults).includes(o.name)) {
            d = code(defaults[o.name]);
        }
        out.push(`| \`${o.name}\` | ${typeCell(o.type)} | ${d} | ${cell(o.doc)} |`);
    }
    return out;
}

/**
 * The algorithm section.
 * @param src - the checker
 * @returns the markdown lines
 */
function algorithms(src: Source): string[] {
    const index = src.exportsOf("src/index.ts");
    const methods = src.typeOf(index.get("GraphtyAlgorithms") as ts.Symbol);
    const common = src.options(src.typeOf(index.get("AlgorithmOptions") as ts.Symbol));
    const out = [
        "### Options every algorithm takes",
        "",
        ...table(common),
        "",
        `The algorithms defined only for directed graphs (${[...DIRECTED_ALGORITHMS]
            .map((k) => `\`graphty${k.charAt(0).toUpperCase()}${k.slice(1)}\``)
            .join(", ")}) default \`directed\` to \`true\`.`,
        "",
        "### Every algorithm",
        "",
        "Each method below exists on every collection and on the core. A method marked **GPU** also has an",
        "`...Async` twin that takes the same options and may run on the GPU (see [WebGPU](#webgpu)).",
        "",
    ];
    for (const name of [...ALGORITHM_NAMES].sort()) {
        const sym = methods.getProperty(name);
        if (sym === undefined) {
            throw new Error(`GraphtyAlgorithms has no ${name}`);
        }
        const key = name.charAt("graphty".length).toLowerCase() + name.slice("graphty".length + 1);
        const param = src.param(src.checker.getTypeOfSymbol(sym), 0);
        const own = param === undefined ? [] : src.options(param).filter((o) => !COMMON_ALGORITHM.includes(o.name));
        const gpu = ASYNC_ALGORITHM_NAMES.includes(`${name}Async`) ? " (**GPU**)" : "";
        out.push(`#### \`${name}\`${gpu}`, "");
        out.push(
            ...(own.length === 0 ? ["No options of its own.", ""] : [...table(own, ALGORITHM_DEFAULTS[key] ?? {}), ""]),
        );
    }
    return out;
}

/**
 * The layout section.
 * @param src - the checker
 * @returns the markdown lines
 */
function layouts(src: Source): string[] {
    const index = src.exportsOf("src/index.ts");
    const lib = src.exportsOf("src/layouts.ts", "@graphty/layout");
    const all = src.options(src.typeOf(index.get("GraphtyLayoutOptions") as ts.Symbol));
    const perLayout = new Set(Object.values(PER_LAYOUT_EXTENSION).flat());
    const shared = all.filter((o) => o.name !== "name" && o.name !== "eles" && !perLayout.has(o.name));
    const sharedNames = new Set(shared.map((o) => o.name));
    const out = [
        "### Options every layout takes",
        "",
        ...table(shared, LAYOUT_DEFAULTS),
        "",
        "### Every layout",
        "",
        "Pass the name to `cy.layout({ name, ... })`. A **simulation** steps a force model and can run on the GPU; a",
        "**static** layout computes once on the CPU. An option that takes per-node arrays or a node column name is",
        "the @graphty/layout function's own and reads the graph-format snapshot of the laid-out nodes, in the node",
        'order of `toSnapshot(cy.nodes().not(":parent"))` (see [Using the graph-format snapshot',
        "directly](#using-the-graph-format-snapshot-directly)).",
        "",
    ];
    for (const name of LAYOUT_NAMES) {
        const simulation = SIMULATIONS[name];
        const libType =
            name in SIMULATION_TYPES
                ? src.typeOf(lib.get(SIMULATION_TYPES[name]) as ts.Symbol)
                : src.param(
                      src.typeOf(lib.get(name.replace(/-(\w)/g, (_, c: string) => c.toUpperCase())) as ts.Symbol),
                      1,
                  );
        if (libType === undefined) {
            throw new Error(`no @graphty/layout options type for graphty-${name}`);
        }
        const own = [
            ...(PER_LAYOUT_EXTENSION[name] ?? []).map((n) => all.find((o) => o.name === n) as Option),
            ...src
                .options(libType)
                .filter(
                    (o) =>
                        !sharedNames.has(o.name) &&
                        !SET_BY_EXTENSION.has(o.name) &&
                        !(PER_LAYOUT_EXTENSION[name] ?? []).includes(o.name),
                ),
        ].map((o) => ({ ...o, required: false }));
        out.push(`#### \`graphty-${name}\` (${simulation === undefined ? "static" : "simulation"})`, "");
        out.push(
            ...(own.length === 0
                ? ["No options of its own.", ""]
                : [...table(own, simulation === undefined ? {} : (SIMULATION_DEFAULTS[simulation] ?? {})), ""]),
        );
    }
    return out;
}

/**
 * What a generator makes, in a few words: its doc's first sentence up to the first colon, citation or quoted title.
 * @param summary - the first sentence
 * @returns the short form
 */
function shortSummary(text: string): string {
    const summary = text.replace(/\s+/g, " ");
    let end = summary.length;
    const colon = summary.indexOf(":");
    if (colon > 0) {
        end = colon;
    }
    const quote = summary.indexOf(', "');
    if (quote > 0 && quote < end) {
        end = quote;
    }
    // a parenthesis holding a year or a page number, starting with an initial, or left open by the sentence split
    // (at an abbreviated journal name) is a citation
    for (const m of summary.matchAll(/ \(/g)) {
        let depth = 0;
        let close = m.index + 1;
        for (; close < summary.length; close++) {
            if (summary[close] === "(") {
                depth++;
            } else if (summary[close] === ")" && --depth === 0) {
                break;
            }
        }
        const inner = summary.slice(m.index, close);
        if (m.index < end && (/\d/.test(inner) || /^ \([A-Z]\./.test(inner) || close === summary.length)) {
            end = m.index;
            break;
        }
    }
    return summary.slice(0, end).replace(/[\s.,;]+$/, "");
}

/**
 * The generator and dataset section.
 * @param src - the checker
 * @returns the markdown lines
 */
function samples(src: Source): string[] {
    const gens = src.typeOf(src.exportsOf("src/samples.ts").get("GENERATORS") as ts.Symbol);
    const lib = src.exportsOf("src/samples.ts", "@graphty/graph-samples/generators");
    const out = [
        "### Generators",
        "",
        "`cy.graphtyGenerate(name, options)`. The options marked `?` are optional; a random generator's `seed`",
        "defaults to 0, and the same options give the same graph on every platform.",
        "",
        "| Name | Options | What it makes |",
        "| --- | --- | --- |",
    ];
    for (const name of Object.keys(GENERATORS)) {
        const fn = gens.getProperty(name);
        const param = fn === undefined ? undefined : src.param(src.checker.getTypeOfSymbol(fn), 0);
        const opts = param === undefined ? [] : src.options(param);
        const libName = `${name.replace(/-(\w)/g, (_, c: string) => c.toUpperCase())}Graph`;
        const libSym =
            lib.get(libName) ?? lib.get(libName.replace(/Graph$/, "")) ?? lib.get(libName.replace(/Graph$/, "Network"));
        let what = libSym === undefined ? "" : shortSummary(src.summary(libSym));
        if (name === "named") {
            what = "A named graph from the literature, by `name`.";
        }
        out.push(
            `| \`${name}\` | ${opts.map((o) => `\`${o.name}${o.required ? "" : "?"}\``).join(", ")} | ${cell(what)} |`,
        );
    }
    out.push(
        "",
        "### Datasets",
        "",
        "`cy.graphtyDataset(name)`. The bundled ones ship inside the package and load without a network; the hosted",
        "ones are downloaded from graphty.app. Each is the work of its authors, under its own license, not this",
        "package's: cite the source when you publish results from one, and check the license before you redistribute it.",
        "",
        "| Name | Nodes | Edges | Directed | Where | License | Source |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    );
    for (const d of Object.values(DATASETS)) {
        const where = BUNDLED_DATASET_NAMES.includes(d.name) ? "bundled" : "hosted";
        out.push(
            `| \`${d.name}\` | ${d.nodes} | ${d.edges} | ${d.directed ? "yes" : "no"} | ${where} | ${cell(d.license)} | <${d.source}> |`,
        );
    }
    return out;
}

/**
 * The file format section.
 * @param src - the checker
 * @returns the markdown lines
 */
function formats(src: Source): string[] {
    const index = src.exportsOf("src/index.ts");
    const members = (alias: string): string[] =>
        (src.typeOf(index.get(alias) as ts.Symbol) as ts.UnionType).types.map((t) => (t as ts.StringLiteralType).value);
    const imports = members("ImportFormat");
    const exports = new Set(members("ExportFormat"));
    return [
        "### File formats",
        "",
        "| Format | Import | Export |",
        "| --- | --- | --- |",
        ...imports.filter((f) => f !== "auto").map((f) => `| \`${f}\` | yes | ${exports.has(f) ? "yes" : "no"} |`),
        "",
        'Import also takes `"auto"`, the default, which detects the format from the content.',
    ];
}

/**
 * The generated reference.
 * @returns the markdown between the markers, without them
 */
export function reference(): string {
    const src = new Source();
    return [
        "## Reference",
        "",
        "Every option below is read from the package's TypeScript types and their doc comments, and each default from",
        "the value this package passes or, where it passes none, from the doc comment of the library that applies it.",
        "So this section always matches the code of the version you installed.",
        "",
        ...layouts(src),
        ...algorithms(src),
        ...samples(src),
        "",
        ...formats(src),
    ].join("\n");
}

/**
 * README.md with its reference replaced, formatted as the repository's Prettier configuration formats it (so the
 * format check and this generator agree on every byte).
 * @param readme - the current README
 * @returns the new README
 */
export async function withReference(readme: string): Promise<string> {
    const start = readme.indexOf(BEGIN);
    const end = readme.indexOf(END);
    if (start < 0 || end < start) {
        throw new Error("README.md has no reference markers");
    }
    const text = `${readme.slice(0, start + BEGIN.length)}\n\n${reference()}\n\n${readme.slice(end)}`;
    const filepath = `${pkg}README.md`;
    return format(text, { ...(await resolveConfig(filepath)), filepath });
}
