import {LayoutEngine} from "./LayoutEngine";
import {SpiralLayout} from "./SpiralLayoutEngine";
import {CircularLayout} from "./CircularLayoutEngine";
import {ShellLayout} from "./ShellLayoutEngine";
import {RandomLayout} from "./RandomLayoutEngine";
import {SpringLayout} from "./SpringLayoutEngine";
import {PlanarLayout} from "./PlanarLayoutEngine";
import {KamadaKawaiLayout} from "./KamadaKawaiLayoutEngine";
import {ForceAtlas2Layout} from "./ForceAtlas2LayoutEngine";
import {ArfLayout} from "./ArfLayoutEngine";
import {SpectralLayout} from "./SpectralLayoutEngine";
import {BfsLayout} from "./BfsLayoutEngine";
import {BipartiteLayout} from "./BipartiteLayoutEngine";
import {MultipartiteLayout} from "./MultipartiteLayoutEngine";
import {D3GraphEngine} from "./D3GraphLayoutEngine";
import {NGraphEngine} from "./NGraphLayoutEngine";

LayoutEngine.register(D3GraphEngine);
LayoutEngine.register(NGraphEngine);
LayoutEngine.register(SpiralLayout);
LayoutEngine.register(CircularLayout);
LayoutEngine.register(ShellLayout);
LayoutEngine.register(RandomLayout);
LayoutEngine.register(SpringLayout);
LayoutEngine.register(PlanarLayout);
LayoutEngine.register(KamadaKawaiLayout);
LayoutEngine.register(ForceAtlas2Layout);
LayoutEngine.register(ArfLayout);
LayoutEngine.register(SpectralLayout);
LayoutEngine.register(BfsLayout);
LayoutEngine.register(BipartiteLayout);
LayoutEngine.register(MultipartiteLayout);
