# THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT graphty/scripts/write-sample-gml.ts
graph [
  directed 0
  node [
    id 0
    graphty_originalId "Acciaiuoli"
    name "Acciaiuoli"
  ]
  node [
    id 1
    graphty_originalId "Medici"
    name "Medici"
  ]
  node [
    id 2
    graphty_originalId "Castellani"
    name "Castellani"
  ]
  node [
    id 3
    graphty_originalId "Peruzzi"
    name "Peruzzi"
  ]
  node [
    id 4
    graphty_originalId "Strozzi"
    name "Strozzi"
  ]
  node [
    id 5
    graphty_originalId "Barbadori"
    name "Barbadori"
  ]
  node [
    id 6
    graphty_originalId "Ridolfi"
    name "Ridolfi"
  ]
  node [
    id 7
    graphty_originalId "Tornabuoni"
    name "Tornabuoni"
  ]
  node [
    id 8
    graphty_originalId "Albizzi"
    name "Albizzi"
  ]
  node [
    id 9
    graphty_originalId "Salviati"
    name "Salviati"
  ]
  node [
    id 10
    graphty_originalId "Pazzi"
    name "Pazzi"
  ]
  node [
    id 11
    graphty_originalId "Bischeri"
    name "Bischeri"
  ]
  node [
    id 12
    graphty_originalId "Guadagni"
    name "Guadagni"
  ]
  node [
    id 13
    graphty_originalId "Ginori"
    name "Ginori"
  ]
  node [
    id 14
    graphty_originalId "Lamberteschi"
    name "Lamberteschi"
  ]
  edge [
    source 0
    target 1
  ]
  edge [
    source 2
    target 3
  ]
  edge [
    source 2
    target 4
  ]
  edge [
    source 2
    target 5
  ]
  edge [
    source 1
    target 5
  ]
  edge [
    source 1
    target 6
  ]
  edge [
    source 1
    target 7
  ]
  edge [
    source 1
    target 8
  ]
  edge [
    source 1
    target 9
  ]
  edge [
    source 9
    target 10
  ]
  edge [
    source 3
    target 4
  ]
  edge [
    source 3
    target 11
  ]
  edge [
    source 4
    target 6
  ]
  edge [
    source 4
    target 11
  ]
  edge [
    source 6
    target 7
  ]
  edge [
    source 7
    target 12
  ]
  edge [
    source 8
    target 13
  ]
  edge [
    source 8
    target 12
  ]
  edge [
    source 11
    target 12
  ]
  edge [
    source 12
    target 14
  ]
]
