# THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT graphty/scripts/write-sample-gml.ts
graph [
  directed 0
  node [
    id 0
    graphty_originalId "Napoleon"
    name "Napoleon"
  ]
  node [
    id 1
    graphty_originalId "Myriel"
    name "Myriel"
  ]
  node [
    id 2
    graphty_originalId "MlleBaptistine"
    name "Mlle Baptistine"
  ]
  node [
    id 3
    graphty_originalId "MmeMagloire"
    name "Mme Magloire"
  ]
  node [
    id 4
    graphty_originalId "CountessDeLo"
    name "Countess de Lo"
  ]
  node [
    id 5
    graphty_originalId "Geborand"
    name "Geborand"
  ]
  node [
    id 6
    graphty_originalId "Champtercier"
    name "Champtercier"
  ]
  node [
    id 7
    graphty_originalId "Cravatte"
    name "Cravatte"
  ]
  node [
    id 8
    graphty_originalId "Count"
    name "Count"
  ]
  node [
    id 9
    graphty_originalId "OldMan"
    name "Old Man"
  ]
  node [
    id 10
    graphty_originalId "Valjean"
    name "Valjean"
  ]
  node [
    id 11
    graphty_originalId "Labarre"
    name "Labarre"
  ]
  node [
    id 12
    graphty_originalId "Marguerite"
    name "Marguerite"
  ]
  node [
    id 13
    graphty_originalId "MmeDeR"
    name "Mme de R"
  ]
  node [
    id 14
    graphty_originalId "Isabeau"
    name "Isabeau"
  ]
  node [
    id 15
    graphty_originalId "Gervais"
    name "Gervais"
  ]
  node [
    id 16
    graphty_originalId "Listolier"
    name "Listolier"
  ]
  node [
    id 17
    graphty_originalId "Tholomyes"
    name "Tholomyes"
  ]
  node [
    id 18
    graphty_originalId "Fameuil"
    name "Fameuil"
  ]
  node [
    id 19
    graphty_originalId "Blacheville"
    name "Blacheville"
  ]
  node [
    id 20
    graphty_originalId "Favourite"
    name "Favourite"
  ]
  node [
    id 21
    graphty_originalId "Dahlia"
    name "Dahlia"
  ]
  node [
    id 22
    graphty_originalId "Zephine"
    name "Zephine"
  ]
  node [
    id 23
    graphty_originalId "Fantine"
    name "Fantine"
  ]
  node [
    id 24
    graphty_originalId "MmeThenardier"
    name "Mme Thenardier"
  ]
  node [
    id 25
    graphty_originalId "Thenardier"
    name "Thenardier"
  ]
  node [
    id 26
    graphty_originalId "Cosette"
    name "Cosette"
  ]
  node [
    id 27
    graphty_originalId "Javert"
    name "Javert"
  ]
  node [
    id 28
    graphty_originalId "Fauchelevent"
    name "Fauchelevent"
  ]
  node [
    id 29
    graphty_originalId "Bamatabois"
    name "Bamatabois"
  ]
  node [
    id 30
    graphty_originalId "Perpetue"
    name "Perpetue"
  ]
  node [
    id 31
    graphty_originalId "Simplice"
    name "Simplice"
  ]
  node [
    id 32
    graphty_originalId "Scaufflaire"
    name "Scaufflaire"
  ]
  node [
    id 33
    graphty_originalId "Woman1"
    name "Woman 1"
  ]
  node [
    id 34
    graphty_originalId "Judge"
    name "Judge"
  ]
  node [
    id 35
    graphty_originalId "Champmathieu"
    name "Champmathieu"
  ]
  node [
    id 36
    graphty_originalId "Brevet"
    name "Brevet"
  ]
  node [
    id 37
    graphty_originalId "Chenildieu"
    name "Chenildieu"
  ]
  node [
    id 38
    graphty_originalId "Cochepaille"
    name "Cochepaille"
  ]
  node [
    id 39
    graphty_originalId "Pontmercy"
    name "Pontmercy"
  ]
  node [
    id 40
    graphty_originalId "Boulatruelle"
    name "Boulatruelle"
  ]
  node [
    id 41
    graphty_originalId "Eponine"
    name "Eponine"
  ]
  node [
    id 42
    graphty_originalId "Anzelma"
    name "Anzelma"
  ]
  node [
    id 43
    graphty_originalId "Woman2"
    name "Woman 2"
  ]
  node [
    id 44
    graphty_originalId "MotherInnocent"
    name "Mother Innocent"
  ]
  node [
    id 45
    graphty_originalId "Gribier"
    name "Gribier"
  ]
  node [
    id 46
    graphty_originalId "MmeBurgon"
    name "Mme Burgon"
  ]
  node [
    id 47
    graphty_originalId "Jondrette"
    name "Jondrette"
  ]
  node [
    id 48
    graphty_originalId "Gavroche"
    name "Gavroche"
  ]
  node [
    id 49
    graphty_originalId "Gillenormand"
    name "Gillenormand"
  ]
  node [
    id 50
    graphty_originalId "Magnon"
    name "Magnon"
  ]
  node [
    id 51
    graphty_originalId "MlleGillenormand"
    name "Mlle Gillenormand"
  ]
  node [
    id 52
    graphty_originalId "MmePontmercy"
    name "Mme Pontmercy"
  ]
  node [
    id 53
    graphty_originalId "MlleVaubois"
    name "Mlle Vaubois"
  ]
  node [
    id 54
    graphty_originalId "LtGillenormand"
    name "Lt Gillenormand"
  ]
  node [
    id 55
    graphty_originalId "Marius"
    name "Marius"
  ]
  node [
    id 56
    graphty_originalId "BaronessT"
    name "Baroness T"
  ]
  node [
    id 57
    graphty_originalId "Mabeuf"
    name "Mabeuf"
  ]
  node [
    id 58
    graphty_originalId "Enjolras"
    name "Enjolras"
  ]
  node [
    id 59
    graphty_originalId "Combeferre"
    name "Combeferre"
  ]
  node [
    id 60
    graphty_originalId "Prouvaire"
    name "Prouvaire"
  ]
  node [
    id 61
    graphty_originalId "Feuilly"
    name "Feuilly"
  ]
  node [
    id 62
    graphty_originalId "Courfeyrac"
    name "Courfeyrac"
  ]
  node [
    id 63
    graphty_originalId "Bahorel"
    name "Bahorel"
  ]
  node [
    id 64
    graphty_originalId "Bossuet"
    name "Bossuet"
  ]
  node [
    id 65
    graphty_originalId "Joly"
    name "Joly"
  ]
  node [
    id 66
    graphty_originalId "Grantaire"
    name "Grantaire"
  ]
  node [
    id 67
    graphty_originalId "MotherPlutarch"
    name "Mother Plutarch"
  ]
  node [
    id 68
    graphty_originalId "Gueulemer"
    name "Gueulemer"
  ]
  node [
    id 69
    graphty_originalId "Babet"
    name "Babet"
  ]
  node [
    id 70
    graphty_originalId "Claquesous"
    name "Claquesous"
  ]
  node [
    id 71
    graphty_originalId "Montparnasse"
    name "Montparnasse"
  ]
  node [
    id 72
    graphty_originalId "Toussaint"
    name "Toussaint"
  ]
  node [
    id 73
    graphty_originalId "Child1"
    name "Child 1"
  ]
  node [
    id 74
    graphty_originalId "Child2"
    name "Child 2"
  ]
  node [
    id 75
    graphty_originalId "Brujon"
    name "Brujon"
  ]
  node [
    id 76
    graphty_originalId "MmeHucheloup"
    name "Mme Hucheloup"
  ]
  edge [
    source 0
    target 1
    shared_chapters 1.0
  ]
  edge [
    source 2
    target 1
    shared_chapters 8.0
  ]
  edge [
    source 3
    target 1
    shared_chapters 10.0
  ]
  edge [
    source 3
    target 2
    shared_chapters 6.0
  ]
  edge [
    source 4
    target 1
    shared_chapters 1.0
  ]
  edge [
    source 5
    target 1
    shared_chapters 1.0
  ]
  edge [
    source 6
    target 1
    shared_chapters 1.0
  ]
  edge [
    source 7
    target 1
    shared_chapters 1.0
  ]
  edge [
    source 8
    target 1
    shared_chapters 2.0
  ]
  edge [
    source 9
    target 1
    shared_chapters 1.0
  ]
  edge [
    source 10
    target 11
    shared_chapters 1.0
  ]
  edge [
    source 10
    target 3
    shared_chapters 3.0
  ]
  edge [
    source 10
    target 2
    shared_chapters 3.0
  ]
  edge [
    source 10
    target 1
    shared_chapters 5.0
  ]
  edge [
    source 12
    target 10
    shared_chapters 1.0
  ]
  edge [
    source 13
    target 10
    shared_chapters 1.0
  ]
  edge [
    source 14
    target 10
    shared_chapters 1.0
  ]
  edge [
    source 15
    target 10
    shared_chapters 1.0
  ]
  edge [
    source 16
    target 17
    shared_chapters 4.0
  ]
  edge [
    source 18
    target 17
    shared_chapters 4.0
  ]
  edge [
    source 18
    target 16
    shared_chapters 4.0
  ]
  edge [
    source 19
    target 17
    shared_chapters 4.0
  ]
  edge [
    source 19
    target 16
    shared_chapters 4.0
  ]
  edge [
    source 19
    target 18
    shared_chapters 4.0
  ]
  edge [
    source 20
    target 17
    shared_chapters 3.0
  ]
  edge [
    source 20
    target 16
    shared_chapters 3.0
  ]
  edge [
    source 20
    target 18
    shared_chapters 3.0
  ]
  edge [
    source 20
    target 19
    shared_chapters 4.0
  ]
  edge [
    source 21
    target 17
    shared_chapters 3.0
  ]
  edge [
    source 21
    target 16
    shared_chapters 3.0
  ]
  edge [
    source 21
    target 18
    shared_chapters 3.0
  ]
  edge [
    source 21
    target 19
    shared_chapters 3.0
  ]
  edge [
    source 21
    target 20
    shared_chapters 5.0
  ]
  edge [
    source 22
    target 17
    shared_chapters 3.0
  ]
  edge [
    source 22
    target 16
    shared_chapters 3.0
  ]
  edge [
    source 22
    target 18
    shared_chapters 3.0
  ]
  edge [
    source 22
    target 19
    shared_chapters 3.0
  ]
  edge [
    source 22
    target 20
    shared_chapters 4.0
  ]
  edge [
    source 22
    target 21
    shared_chapters 4.0
  ]
  edge [
    source 23
    target 17
    shared_chapters 3.0
  ]
  edge [
    source 23
    target 16
    shared_chapters 3.0
  ]
  edge [
    source 23
    target 18
    shared_chapters 3.0
  ]
  edge [
    source 23
    target 19
    shared_chapters 3.0
  ]
  edge [
    source 23
    target 20
    shared_chapters 4.0
  ]
  edge [
    source 23
    target 21
    shared_chapters 4.0
  ]
  edge [
    source 23
    target 22
    shared_chapters 4.0
  ]
  edge [
    source 23
    target 12
    shared_chapters 2.0
  ]
  edge [
    source 23
    target 10
    shared_chapters 9.0
  ]
  edge [
    source 24
    target 23
    shared_chapters 2.0
  ]
  edge [
    source 24
    target 10
    shared_chapters 7.0
  ]
  edge [
    source 25
    target 24
    shared_chapters 13.0
  ]
  edge [
    source 25
    target 23
    shared_chapters 1.0
  ]
  edge [
    source 25
    target 10
    shared_chapters 12.0
  ]
  edge [
    source 26
    target 24
    shared_chapters 4.0
  ]
  edge [
    source 26
    target 10
    shared_chapters 31.0
  ]
  edge [
    source 26
    target 17
    shared_chapters 1.0
  ]
  edge [
    source 26
    target 25
    shared_chapters 1.0
  ]
  edge [
    source 27
    target 10
    shared_chapters 17.0
  ]
  edge [
    source 27
    target 23
    shared_chapters 5.0
  ]
  edge [
    source 27
    target 25
    shared_chapters 5.0
  ]
  edge [
    source 27
    target 24
    shared_chapters 1.0
  ]
  edge [
    source 27
    target 26
    shared_chapters 1.0
  ]
  edge [
    source 28
    target 10
    shared_chapters 8.0
  ]
  edge [
    source 28
    target 27
    shared_chapters 1.0
  ]
  edge [
    source 29
    target 23
    shared_chapters 1.0
  ]
  edge [
    source 29
    target 27
    shared_chapters 1.0
  ]
  edge [
    source 29
    target 10
    shared_chapters 2.0
  ]
  edge [
    source 30
    target 23
    shared_chapters 1.0
  ]
  edge [
    source 31
    target 30
    shared_chapters 2.0
  ]
  edge [
    source 31
    target 10
    shared_chapters 3.0
  ]
  edge [
    source 31
    target 23
    shared_chapters 2.0
  ]
  edge [
    source 31
    target 27
    shared_chapters 1.0
  ]
  edge [
    source 32
    target 10
    shared_chapters 1.0
  ]
  edge [
    source 33
    target 10
    shared_chapters 2.0
  ]
  edge [
    source 33
    target 27
    shared_chapters 1.0
  ]
  edge [
    source 34
    target 10
    shared_chapters 3.0
  ]
  edge [
    source 34
    target 29
    shared_chapters 2.0
  ]
  edge [
    source 35
    target 10
    shared_chapters 3.0
  ]
  edge [
    source 35
    target 34
    shared_chapters 3.0
  ]
  edge [
    source 35
    target 29
    shared_chapters 2.0
  ]
  edge [
    source 36
    target 34
    shared_chapters 2.0
  ]
  edge [
    source 36
    target 35
    shared_chapters 2.0
  ]
  edge [
    source 36
    target 10
    shared_chapters 2.0
  ]
  edge [
    source 36
    target 29
    shared_chapters 1.0
  ]
  edge [
    source 37
    target 34
    shared_chapters 2.0
  ]
  edge [
    source 37
    target 35
    shared_chapters 2.0
  ]
  edge [
    source 37
    target 36
    shared_chapters 2.0
  ]
  edge [
    source 37
    target 10
    shared_chapters 2.0
  ]
  edge [
    source 37
    target 29
    shared_chapters 1.0
  ]
  edge [
    source 38
    target 34
    shared_chapters 2.0
  ]
  edge [
    source 38
    target 35
    shared_chapters 2.0
  ]
  edge [
    source 38
    target 36
    shared_chapters 2.0
  ]
  edge [
    source 38
    target 37
    shared_chapters 2.0
  ]
  edge [
    source 38
    target 10
    shared_chapters 2.0
  ]
  edge [
    source 38
    target 29
    shared_chapters 1.0
  ]
  edge [
    source 39
    target 25
    shared_chapters 1.0
  ]
  edge [
    source 40
    target 25
    shared_chapters 1.0
  ]
  edge [
    source 41
    target 24
    shared_chapters 2.0
  ]
  edge [
    source 41
    target 25
    shared_chapters 3.0
  ]
  edge [
    source 42
    target 41
    shared_chapters 2.0
  ]
  edge [
    source 42
    target 25
    shared_chapters 2.0
  ]
  edge [
    source 42
    target 24
    shared_chapters 1.0
  ]
  edge [
    source 43
    target 10
    shared_chapters 3.0
  ]
  edge [
    source 43
    target 26
    shared_chapters 1.0
  ]
  edge [
    source 43
    target 27
    shared_chapters 1.0
  ]
  edge [
    source 44
    target 28
    shared_chapters 3.0
  ]
  edge [
    source 44
    target 10
    shared_chapters 1.0
  ]
  edge [
    source 45
    target 28
    shared_chapters 2.0
  ]
  edge [
    source 46
    target 47
    shared_chapters 1.0
  ]
  edge [
    source 48
    target 46
    shared_chapters 2.0
  ]
  edge [
    source 48
    target 25
    shared_chapters 1.0
  ]
  edge [
    source 48
    target 27
    shared_chapters 1.0
  ]
  edge [
    source 48
    target 10
    shared_chapters 1.0
  ]
  edge [
    source 49
    target 26
    shared_chapters 3.0
  ]
  edge [
    source 49
    target 10
    shared_chapters 2.0
  ]
  edge [
    source 50
    target 49
    shared_chapters 1.0
  ]
  edge [
    source 50
    target 24
    shared_chapters 1.0
  ]
  edge [
    source 51
    target 49
    shared_chapters 9.0
  ]
  edge [
    source 51
    target 26
    shared_chapters 2.0
  ]
  edge [
    source 51
    target 10
    shared_chapters 2.0
  ]
  edge [
    source 52
    target 51
    shared_chapters 1.0
  ]
  edge [
    source 52
    target 39
    shared_chapters 1.0
  ]
  edge [
    source 53
    target 51
    shared_chapters 1.0
  ]
  edge [
    source 54
    target 51
    shared_chapters 2.0
  ]
  edge [
    source 54
    target 49
    shared_chapters 1.0
  ]
  edge [
    source 54
    target 26
    shared_chapters 1.0
  ]
  edge [
    source 55
    target 51
    shared_chapters 6.0
  ]
  edge [
    source 55
    target 49
    shared_chapters 12.0
  ]
  edge [
    source 55
    target 39
    shared_chapters 1.0
  ]
  edge [
    source 55
    target 54
    shared_chapters 1.0
  ]
  edge [
    source 55
    target 26
    shared_chapters 21.0
  ]
  edge [
    source 55
    target 10
    shared_chapters 19.0
  ]
  edge [
    source 55
    target 17
    shared_chapters 1.0
  ]
  edge [
    source 55
    target 25
    shared_chapters 2.0
  ]
  edge [
    source 55
    target 41
    shared_chapters 5.0
  ]
  edge [
    source 55
    target 48
    shared_chapters 4.0
  ]
  edge [
    source 56
    target 49
    shared_chapters 1.0
  ]
  edge [
    source 56
    target 55
    shared_chapters 1.0
  ]
  edge [
    source 57
    target 55
    shared_chapters 1.0
  ]
  edge [
    source 57
    target 41
    shared_chapters 1.0
  ]
  edge [
    source 57
    target 48
    shared_chapters 1.0
  ]
  edge [
    source 58
    target 55
    shared_chapters 7.0
  ]
  edge [
    source 58
    target 48
    shared_chapters 7.0
  ]
  edge [
    source 58
    target 27
    shared_chapters 6.0
  ]
  edge [
    source 58
    target 57
    shared_chapters 1.0
  ]
  edge [
    source 58
    target 10
    shared_chapters 4.0
  ]
  edge [
    source 59
    target 58
    shared_chapters 15.0
  ]
  edge [
    source 59
    target 55
    shared_chapters 5.0
  ]
  edge [
    source 59
    target 48
    shared_chapters 6.0
  ]
  edge [
    source 59
    target 57
    shared_chapters 2.0
  ]
  edge [
    source 60
    target 48
    shared_chapters 1.0
  ]
  edge [
    source 60
    target 58
    shared_chapters 4.0
  ]
  edge [
    source 60
    target 59
    shared_chapters 2.0
  ]
  edge [
    source 61
    target 48
    shared_chapters 2.0
  ]
  edge [
    source 61
    target 58
    shared_chapters 6.0
  ]
  edge [
    source 61
    target 60
    shared_chapters 2.0
  ]
  edge [
    source 61
    target 59
    shared_chapters 5.0
  ]
  edge [
    source 61
    target 57
    shared_chapters 1.0
  ]
  edge [
    source 61
    target 55
    shared_chapters 1.0
  ]
  edge [
    source 62
    target 55
    shared_chapters 9.0
  ]
  edge [
    source 62
    target 58
    shared_chapters 17.0
  ]
  edge [
    source 62
    target 59
    shared_chapters 13.0
  ]
  edge [
    source 62
    target 48
    shared_chapters 7.0
  ]
  edge [
    source 62
    target 57
    shared_chapters 2.0
  ]
  edge [
    source 62
    target 41
    shared_chapters 1.0
  ]
  edge [
    source 62
    target 61
    shared_chapters 6.0
  ]
  edge [
    source 62
    target 60
    shared_chapters 3.0
  ]
  edge [
    source 63
    target 59
    shared_chapters 5.0
  ]
  edge [
    source 63
    target 48
    shared_chapters 5.0
  ]
  edge [
    source 63
    target 62
    shared_chapters 6.0
  ]
  edge [
    source 63
    target 57
    shared_chapters 2.0
  ]
  edge [
    source 63
    target 58
    shared_chapters 4.0
  ]
  edge [
    source 63
    target 61
    shared_chapters 3.0
  ]
  edge [
    source 63
    target 60
    shared_chapters 2.0
  ]
  edge [
    source 63
    target 55
    shared_chapters 1.0
  ]
  edge [
    source 64
    target 55
    shared_chapters 5.0
  ]
  edge [
    source 64
    target 62
    shared_chapters 12.0
  ]
  edge [
    source 64
    target 48
    shared_chapters 5.0
  ]
  edge [
    source 64
    target 63
    shared_chapters 4.0
  ]
  edge [
    source 64
    target 58
    shared_chapters 10.0
  ]
  edge [
    source 64
    target 61
    shared_chapters 6.0
  ]
  edge [
    source 64
    target 60
    shared_chapters 2.0
  ]
  edge [
    source 64
    target 59
    shared_chapters 9.0
  ]
  edge [
    source 64
    target 57
    shared_chapters 1.0
  ]
  edge [
    source 64
    target 10
    shared_chapters 1.0
  ]
  edge [
    source 65
    target 63
    shared_chapters 5.0
  ]
  edge [
    source 65
    target 64
    shared_chapters 7.0
  ]
  edge [
    source 65
    target 48
    shared_chapters 3.0
  ]
  edge [
    source 65
    target 62
    shared_chapters 5.0
  ]
  edge [
    source 65
    target 58
    shared_chapters 5.0
  ]
  edge [
    source 65
    target 61
    shared_chapters 5.0
  ]
  edge [
    source 65
    target 60
    shared_chapters 2.0
  ]
  edge [
    source 65
    target 59
    shared_chapters 5.0
  ]
  edge [
    source 65
    target 57
    shared_chapters 1.0
  ]
  edge [
    source 65
    target 55
    shared_chapters 2.0
  ]
  edge [
    source 66
    target 64
    shared_chapters 3.0
  ]
  edge [
    source 66
    target 58
    shared_chapters 3.0
  ]
  edge [
    source 66
    target 59
    shared_chapters 1.0
  ]
  edge [
    source 66
    target 62
    shared_chapters 2.0
  ]
  edge [
    source 66
    target 65
    shared_chapters 2.0
  ]
  edge [
    source 66
    target 48
    shared_chapters 1.0
  ]
  edge [
    source 66
    target 63
    shared_chapters 1.0
  ]
  edge [
    source 66
    target 61
    shared_chapters 1.0
  ]
  edge [
    source 66
    target 60
    shared_chapters 1.0
  ]
  edge [
    source 67
    target 57
    shared_chapters 3.0
  ]
  edge [
    source 68
    target 25
    shared_chapters 5.0
  ]
  edge [
    source 68
    target 10
    shared_chapters 1.0
  ]
  edge [
    source 68
    target 24
    shared_chapters 1.0
  ]
  edge [
    source 68
    target 27
    shared_chapters 1.0
  ]
  edge [
    source 68
    target 48
    shared_chapters 1.0
  ]
  edge [
    source 68
    target 41
    shared_chapters 1.0
  ]
  edge [
    source 69
    target 25
    shared_chapters 6.0
  ]
  edge [
    source 69
    target 68
    shared_chapters 6.0
  ]
  edge [
    source 69
    target 10
    shared_chapters 1.0
  ]
  edge [
    source 69
    target 24
    shared_chapters 1.0
  ]
  edge [
    source 69
    target 27
    shared_chapters 2.0
  ]
  edge [
    source 69
    target 48
    shared_chapters 1.0
  ]
  edge [
    source 69
    target 41
    shared_chapters 1.0
  ]
  edge [
    source 70
    target 25
    shared_chapters 4.0
  ]
  edge [
    source 70
    target 69
    shared_chapters 4.0
  ]
  edge [
    source 70
    target 68
    shared_chapters 4.0
  ]
  edge [
    source 70
    target 10
    shared_chapters 1.0
  ]
  edge [
    source 70
    target 24
    shared_chapters 1.0
  ]
  edge [
    source 70
    target 27
    shared_chapters 1.0
  ]
  edge [
    source 70
    target 41
    shared_chapters 1.0
  ]
  edge [
    source 70
    target 58
    shared_chapters 1.0
  ]
  edge [
    source 71
    target 27
    shared_chapters 1.0
  ]
  edge [
    source 71
    target 69
    shared_chapters 2.0
  ]
  edge [
    source 71
    target 68
    shared_chapters 2.0
  ]
  edge [
    source 71
    target 70
    shared_chapters 2.0
  ]
  edge [
    source 71
    target 10
    shared_chapters 1.0
  ]
  edge [
    source 71
    target 48
    shared_chapters 1.0
  ]
  edge [
    source 71
    target 41
    shared_chapters 1.0
  ]
  edge [
    source 71
    target 25
    shared_chapters 1.0
  ]
  edge [
    source 72
    target 26
    shared_chapters 2.0
  ]
  edge [
    source 72
    target 27
    shared_chapters 1.0
  ]
  edge [
    source 72
    target 10
    shared_chapters 1.0
  ]
  edge [
    source 73
    target 48
    shared_chapters 2.0
  ]
  edge [
    source 74
    target 48
    shared_chapters 2.0
  ]
  edge [
    source 74
    target 73
    shared_chapters 3.0
  ]
  edge [
    source 75
    target 69
    shared_chapters 3.0
  ]
  edge [
    source 75
    target 68
    shared_chapters 3.0
  ]
  edge [
    source 75
    target 25
    shared_chapters 3.0
  ]
  edge [
    source 75
    target 48
    shared_chapters 1.0
  ]
  edge [
    source 75
    target 41
    shared_chapters 1.0
  ]
  edge [
    source 75
    target 70
    shared_chapters 1.0
  ]
  edge [
    source 75
    target 71
    shared_chapters 1.0
  ]
  edge [
    source 76
    target 64
    shared_chapters 1.0
  ]
  edge [
    source 76
    target 65
    shared_chapters 1.0
  ]
  edge [
    source 76
    target 66
    shared_chapters 1.0
  ]
  edge [
    source 76
    target 63
    shared_chapters 1.0
  ]
  edge [
    source 76
    target 62
    shared_chapters 1.0
  ]
  edge [
    source 76
    target 48
    shared_chapters 1.0
  ]
  edge [
    source 76
    target 58
    shared_chapters 1.0
  ]
]
