import { existsSync, readFileSync } from "node:fs";
import { defineConfig } from "vitepress";
import { loadEnv } from "vite";

// Load environment variables from .env (reuse existing config)
const env = loadEnv("development", process.cwd(), "");

// Try to load typedoc sidebar if it exists (generated by docs:api command)
let typedocSidebar: Array<{ text: string; link: string }> = [];
const sidebarPath = "./docs/api/generated/typedoc-sidebar.json";
if (existsSync(sidebarPath)) {
    typedocSidebar = JSON.parse(readFileSync(sidebarPath, "utf-8"));
}

export default defineConfig({
    vite: {
        server: {
            host: env.HOST || true,
            port: env.DOCS_PORT ? parseInt(env.DOCS_PORT) : 9028,
            https:
                env.HTTPS_KEY_PATH && env.HTTPS_CERT_PATH
                    ? {
                          key: readFileSync(env.HTTPS_KEY_PATH),
                          cert: readFileSync(env.HTTPS_CERT_PATH),
                      }
                    : undefined,
        },
    },

    title: "Graphty Algorithms",
    description: "Graph algorithms library for browser environments",
    // Use /algorithms/docs/ for GitHub Pages project site deployment
    base: "/algorithms/docs/",

    // Ignore dead links during build (API pages link to generated docs)
    ignoreDeadLinks: true,

    vue: {
        template: {
            compilerOptions: {
                // Treat tags that look like type parameters as custom elements
                // to avoid Vue parsing errors in generated API docs
                isCustomElement: (tag) => tag.includes(">"),
            },
        },
    },

    themeConfig: {
        nav: [
            { text: "Guide", link: "/guide/getting-started" },
            { text: "API", link: "/api/" },
            // Points to interactive examples at /algorithms/
            { text: "Examples", link: "/examples/" },
        ],

        sidebar: {
            "/guide/": [
                {
                    text: "Introduction",
                    items: [
                        { text: "Getting Started", link: "/guide/getting-started" },
                        { text: "Installation", link: "/guide/installation" },
                    ],
                },
                {
                    text: "Core Concepts",
                    items: [
                        { text: "Graph Data Structure", link: "/guide/graph" },
                        { text: "Traversal Algorithms", link: "/guide/traversal" },
                        { text: "Shortest Path", link: "/guide/shortest-path" },
                        { text: "Centrality", link: "/guide/centrality" },
                    ],
                },
                {
                    text: "Advanced",
                    items: [
                        { text: "Community Detection", link: "/guide/community" },
                        { text: "Clustering", link: "/guide/clustering" },
                        { text: "Flow Algorithms", link: "/guide/flow" },
                        { text: "Link Prediction", link: "/guide/link-prediction" },
                        { text: "Performance", link: "/guide/performance" },
                    ],
                },
            ],
            "/api/": [
                { text: "Overview", link: "/api/" },
                {
                    text: "Core",
                    items: [
                        { text: "Graph", link: "/api/graph" },
                        { text: "Types", link: "/api/types" },
                    ],
                },
                {
                    text: "Algorithms",
                    items: [
                        { text: "Traversal", link: "/api/traversal" },
                        { text: "Shortest Path", link: "/api/shortest-path" },
                        { text: "Centrality", link: "/api/centrality" },
                        { text: "Components", link: "/api/components" },
                        { text: "MST", link: "/api/mst" },
                        { text: "Community", link: "/api/community" },
                        { text: "Clustering", link: "/api/clustering" },
                        { text: "Flow", link: "/api/flow" },
                        { text: "Matching", link: "/api/matching" },
                        { text: "Link Prediction", link: "/api/link-prediction" },
                    ],
                },
                {
                    text: "Generated TypeDoc",
                    collapsed: true,
                    items: typedocSidebar,
                },
            ],
        },

        socialLinks: [{ icon: "github", link: "https://github.com/graphty-org/graphty-monorepo" }],

        search: {
            provider: "local",
        },

        editLink: {
            pattern: "https://github.com/graphty-org/graphty-monorepo/edit/master/algorithms/docs/:path",
        },
    },
});
