import { existsSync, readFileSync } from "node:fs";
import { defineConfig } from "vitepress";
import { loadEnv } from "vite";

// Load environment variables from .env (reuse existing config)
const env = loadEnv("development", process.cwd(), "");

// Try to load typedoc sidebar if it exists (generated by docs:api command)
let typedocSidebar: Array<{ text: string; link: string }> = [];
const sidebarPath = "./docs/api/generated/typedoc-sidebar.json";
if (existsSync(sidebarPath)) {
    typedocSidebar = JSON.parse(readFileSync(sidebarPath, "utf-8"));
}

export default defineConfig({
    vite: {
        server: {
            host: env.HOST || true,
            https:
                env.HTTPS_KEY_PATH && env.HTTPS_CERT_PATH
                    ? {
                          key: readFileSync(env.HTTPS_KEY_PATH),
                          cert: readFileSync(env.HTTPS_CERT_PATH),
                      }
                    : undefined,
        },
    },

    title: "Graphty Algorithms",
    description: "Graph algorithms library for browser environments",
    // Use /algorithms/docs/ for GitHub Pages project site deployment
    base: "/algorithms/docs/",

    vue: {
        template: {
            compilerOptions: {
                // Treat tags that look like type parameters as custom elements
                // to avoid Vue parsing errors in generated API docs
                isCustomElement: (tag) => tag.includes(">"),
            },
        },
    },

    themeConfig: {
        nav: [
            { text: "Guide", link: "/guide/getting-started" },
            { text: "API", link: "/api/" },
            { text: "Examples", link: "https://graphty.app/algorithms/examples/" },
        ],

        sidebar: {
            "/guide/": [
                {
                    text: "Introduction",
                    items: [
                        { text: "Getting Started", link: "/guide/getting-started" },
                        { text: "Installation", link: "/guide/installation" },
                    ],
                },
                {
                    text: "Core Concepts",
                    items: [
                        { text: "Graph Data Structure", link: "/guide/graph" },
                        { text: "Traversal Algorithms", link: "/guide/traversal" },
                        { text: "Shortest Path", link: "/guide/shortest-path" },
                        { text: "Centrality", link: "/guide/centrality" },
                    ],
                },
                {
                    text: "Advanced",
                    items: [
                        { text: "Community Detection", link: "/guide/community" },
                        { text: "Clustering", link: "/guide/clustering" },
                        { text: "Flow Algorithms", link: "/guide/flow" },
                        { text: "Link Prediction", link: "/guide/link-prediction" },
                        { text: "Performance", link: "/guide/performance" },
                    ],
                },
            ],
            "/api/": [
                { text: "Overview", link: "/api/" },
                {
                    text: "Reference",
                    items: [
                        { text: "Graph", link: "/api/generated/core/graph/classes/Graph" },
                        { text: "Types", link: "/api/generated/types/" },
                        { text: "Functions", link: "/api/generated/index/" },
                    ],
                },
                {
                    text: "Generated TypeDoc",
                    collapsed: true,
                    items: typedocSidebar,
                },
            ],
        },

        socialLinks: [{ icon: "github", link: "https://github.com/graphty-org/graphty-monorepo" }],

        search: {
            provider: "local",
        },

        editLink: {
            pattern: "https://github.com/graphty-org/graphty-monorepo/edit/master/algorithms/docs/:path",
        },
    },
});
