// THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE DIRECTLY
// This configuration extends the shared ESLint config from the monorepo root
import { createEslintConfig } from '../eslint.config.base.js';

export default createEslintConfig();
