#!/usr/bin/env node
/**
 * THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT test/helpers/performance-regression.ts
 *
 * CLI entry point for running performance regression tests
 */

import { PerformanceRegressionTest } from "./performance-regression.js";

// Run performance regression tests
const test = new PerformanceRegressionTest();
const updateBaselines = process.argv.includes("--update-baselines");

if (updateBaselines) {
    test.updateBaselines();
} else {
    const success = test.runAll();
    process.exit(success ? 0 : 1);
}
