#!/usr/bin/env node
/**
 * visual-review: capture Storybook stories, compare them with the baselines in git, and serve
 * the page where the owner accepts or rejects the differences.
 *
 * Every command runs in a git checkout and reads its settings from visual-review.config.json at
 * the checkout's root (see config.mjs and the README). `visual-review <command> --help` describes
 * each command. Each command's modules are imported only when it runs, so `gate` needs nothing
 * beyond Node's standard library and runs from a checkout without an install.
 */

import { readFile, readdir } from "node:fs/promises";
import { join, resolve } from "node:path";
import { parseArgs } from "node:util";

const HELP = {
    init: `usage: visual-review init [--force]

Sets up visual review in the current git repository. Writes, at the repository's root:
  visual-review.config.json           the projects to capture and the repository's settings
  .gitattributes                      a rule storing the baseline PNGs in Git LFS
  .gitignore                          an entry for the work directory (downloads, review state)
  .github/workflows/<workflow>        captures every pull request and push, and gates pull requests
  .github/workflows/visual-seed.yml   captures an older commit, to seed baselines from

An existing file is kept, and a line already present is not added again. --force rewrites the
workflows init wrote before (they start with "Generated by visual-review init"), to pick up a
newer template; it never replaces the config or a workflow you wrote. Edit
visual-review.config.json afterwards: it starts with one Storybook built by
\`<package manager> run build-storybook\` into storybook-static/.`,

    capture: `usage: visual-review capture --project <id> --out <dir> [options]

Captures every story of one built Storybook and writes results.json and the PNGs to review into
<dir>. Exits 0 whatever it finds; non-zero only when the tool itself fails, including a baseline
that is an LFS pointer (run \`git lfs pull\`).

  --project <id>          a project of visual-review.config.json
  --out <dir>             where results.json and the PNGs go
  --storybook <dir>       the built Storybook (default: the project's "storybook")
  --baselines <dir>       the baselines (default: <baselines>/<id> from the config)
  --workers <n>           browsers in parallel (default: the project's "workers")
  --reference <dir>       the default branch's capture (from \`reference\`): a story with no
                          baseline that looks as it does there is "unseeded", not "new"
  --stories <prefix,...>  only the story ids starting with a prefix, for a quick local preview`,

    reference: `usage: visual-review reference --project <id> --out <dir>

Downloads the default branch's newest complete capture of the project with gh into <dir> and
prints its directory, or prints nothing when there is none. CI runs it before \`capture\`.`,

    compare: `usage: visual-review compare --baselines <dir> --captures <dir> [--threshold <0..1>] [--include-aa]

Compares every PNG in the two directories by name and prints one JSON line per file that is not
unchanged, then a summary. Exits 1 when anything differs. For local use.`,

    serve: `usage: PORT=<n> visual-review serve [--master-run <id>] [--results <dir>] [--previews <dir>]

Serves the review page on $PORT, bound to $HOST (default localhost). With $HTTPS_CERT_PATH and
$HTTPS_KEY_PATH set it serves HTTPS; without them, plain HTTP, and then only on a loopback HOST.
Lists the open pull requests that have a run of the config's workflow and downloads their
captures with gh. Refuses to start without git-lfs, because an accept would commit raw PNGs.
The URL to open, with its session token, is printed at every start.

  --master-run <id>  also list the default branch at that workflow run, for seeding baselines
  --results <dir>    serve a local directory of <project>/results.json instead, offline, as a
                     preview to look at: gh is never run, nothing can be decided, no Finish
  --previews <dir>   where local previews of pull requests are (<dir>/<pr>/<project>), as a
                     preview script writes them; default: the config's workDir/local in the main
                     checkout of this repository, so every worktree's server finds them. A complete
                     preview of a pull request's head is reviewed and finished like CI's capture
                     until CI's lands; the gate still checks CI's capture against what you accept`,

    gate: null, // gate.mjs's own usage

    notify: `usage: visual-review notify [--command '<json argv>'] [--gap <minutes>]

Runs beside \`serve\` (same checkout) and sends one message when pull requests become ready
for review: images to decide, captures complete. The first goes at once; any more within --gap
minutes (default 10) wait and go together as one message. Nothing new, nothing sent; never for
CI running, failed captures or anything already announced. It reads only the inbox \`serve\`
keeps in <workDir>/state/inbox.json, so it never calls GitHub.

  --command <json>  the program to run and its arguments, as a JSON array; {title}, {message}
                    and {url} are replaced, and no shell runs it. Default: $VISUAL_REVIEW_NOTIFY.
                    The address it sends carries no session token: open it once with the token on
                    each device and the page remembers it.`,

    update: `usage: visual-review update <pull request number>

Merges the default branch into the pull request's branch (a merge commit, never a rebase) and
pushes it, so CI captures again against the default branch's baselines. A file under the
baselines directory that conflicts takes the default branch's side, and the commit names each
one; it accepts nothing, and the review shows whatever still differs. A conflict anywhere else
refuses, lists the files and changes nothing. The commit is signed as your git configuration
signs. For a pull request whose capture is stale against the default branch's baselines, or
whose branch conflicts with it only under the baselines directory.`,

    "install-browser": `usage: visual-review install-browser

Installs the Chromium, and on Linux the system libraries, that this package's Playwright uses
(\`playwright install --with-deps chromium\` of the same Playwright version capture imports).`,
};

const COMMANDS = {
    init,
    capture,
    reference,
    compare,
    serve,
    gate,
    notify,
    update,
    "install-browser": installBrowser,
};

const MAIN_HELP = `usage: visual-review <command> [options]

Screenshots every story of your Storybooks in CI, compares them with baseline PNGs kept in git
(Git LFS), and serves a local page where you accept or reject each difference.

Commands:
  init             set up a repository: config, .gitattributes, GitHub Actions workflows
  capture          screenshot one project's built Storybook and compare with its baselines
  reference        download the default branch's newest capture (CI, before capture)
  gate             fail a pull request that holds changes nobody accepted (CI)
  serve            the review page
  notify           one quiet message when pull requests become ready for review
  update           merge the default branch into a pull request, taking its baselines
  compare          compare two directories of PNGs (local use)
  install-browser  install the Chromium capture uses

\`visual-review <command> --help\` describes each command. Documentation:
https://graphty.app/docs/visual-review/`;

/**
 * The repository and its config, loaded only by the commands that need them.
 * @returns {Promise<{ root: string, config: object }>} the checkout's root and its settings
 */
async function settings() {
    const { loadConfig, repoRoot } = await import("./lib/config.mjs");
    const root = repoRoot();
    return { root, config: loadConfig(root) };
}

async function capture(args) {
    const { values } = parseArgs({
        args,
        options: {
            project: { type: "string" },
            out: { type: "string" },
            storybook: { type: "string" },
            baselines: { type: "string" },
            workers: { type: "string" },
            reference: { type: "string" },
            stories: { type: "string" },
        },
    });
    const { root, config } = await settings();
    const project = Object.hasOwn(config.projects, values.project ?? "") ? config.projects[values.project] : undefined;
    const workers = Number(values.workers ?? project?.workers);
    if (!project || !values.out || !(Number.isInteger(workers) && workers > 0)) {
        console.error(`${HELP.capture}\n\nprojects: ${Object.keys(config.projects).join(", ")}`);
        return 2;
    }
    // Playwright is capture's only dependency, so it loads only for this command.
    const { capture: run } = await import("../capture/capture.mjs");
    await run({
        project: values.project,
        storybook: resolve(values.storybook ?? join(root, project.storybook)),
        baselines: resolve(values.baselines ?? join(root, config.baselines, values.project)),
        out: resolve(values.out),
        workers,
        waitFor: project.waitFor,
        reference: values.reference ? resolve(values.reference) : null,
        stories: values.stories ? values.stories.split(",").filter(Boolean) : null,
        fontconfig: config.fontconfig ? join(root, config.fontconfig) : null,
    });
    return 0;
}

async function reference(args) {
    const { values } = parseArgs({ args, options: { project: { type: "string" }, out: { type: "string" } } });
    if (!values.project || !values.out) {
        console.error(HELP.reference);
        return 2;
    }
    const { root, config } = await settings();
    const { ghRunner, newestMasterCapture } = await import("./lib/github.mjs");
    console.log((await newestMasterCapture(ghRunner(root), values.project, resolve(values.out), config)) ?? "");
    return 0;
}

const LOOPBACK = new Set(["localhost", "127.0.0.1", "::1"]);

async function serve(args) {
    if (args.includes("--branch")) {
        console.error("visual-review serve: --branch is gone: a --results preview is look only and has no Finish");
        return 2;
    }
    const { values } = parseArgs({
        args,
        options: {
            "master-run": { type: "string" },
            results: { type: "string" },
            previews: { type: "string" },
        },
    });
    const { PORT, HOST = "localhost", HTTPS_CERT_PATH, HTTPS_KEY_PATH } = process.env;
    const masterRun = values["master-run"] === undefined ? undefined : Number(values["master-run"]);
    const https = Boolean(HTTPS_CERT_PATH && HTTPS_KEY_PATH);
    if (!PORT || (masterRun !== undefined && !Number.isInteger(masterRun))) {
        console.error(HELP.serve);
        return 2;
    }
    if (!https && !LOOPBACK.has(HOST)) {
        console.error(
            `visual-review serve: HOST=${HOST} is reachable from other machines, so the page needs HTTPS: ` +
                "set HTTPS_CERT_PATH and HTTPS_KEY_PATH, or serve on localhost",
        );
        return 2;
    }
    const { root, config } = await settings();
    const { readFileSync } = await import("node:fs");
    const { lfsProblem } = await import("./lib/accept.mjs");
    const { ghRunner } = await import("./lib/github.mjs");
    const { createApp, sessionToken } = await import("./lib/serve.mjs");
    const lfs = await lfsProblem(root);
    if (lfs) {
        console.error(`visual-review serve: ${lfs}`);
        return 1;
    }
    const tmp = join(root, config.workDir);
    // The main checkout, not this worktree: a preview script run from any worktree writes there.
    const { execFileSync } = await import("node:child_process");
    const { dirname } = await import("node:path");
    const common = execFileSync("git", ["rev-parse", "--path-format=absolute", "--git-common-dir"], { cwd: root })
        .toString("utf8")
        .trim();
    const previews = values.previews ? resolve(values.previews) : join(dirname(common), config.workDir, "local");
    const token = sessionToken(join(tmp, "state"));
    const origin = `${https ? "https" : "http"}://${HOST.includes(":") ? `[${HOST}]` : HOST}:${PORT}`;
    // Offline: a local results directory is a preview, so nothing is posted to GitHub.
    const offline = async (ghArgs, input) => {
        console.log(`gh (offline, not run): ${ghArgs.join(" ")}\n${input ?? ""}`);
        return JSON.stringify({ html_url: null });
    };
    const certs = https ? `HTTPS_CERT_PATH=${HTTPS_CERT_PATH} HTTPS_KEY_PATH=${HTTPS_KEY_PATH} ` : "";
    const app = createApp({
        repo: root,
        gh: values.results ? offline : ghRunner(root),
        config,
        tmp,
        token,
        origin,
        masterRun,
        results: values.results && resolve(values.results),
        warm: true,
        previews: values.results ? null : previews,
        // What the owner types to run this server from their own shell, so Finish signs with
        // their key rather than the environment of whoever started it (an agent, say).
        startCommand:
            `cd ${root} && PORT=${PORT} HOST=${HOST} ${certs}node ${process.argv[1]} serve ${args.join(" ")}`.trim(),
    });
    const server = https
        ? (await import("node:https")).createServer(
              { cert: readFileSync(HTTPS_CERT_PATH), key: readFileSync(HTTPS_KEY_PATH) },
              app,
          )
        : (await import("node:http")).createServer(app);
    await new Promise((done) => server.listen({ port: Number(PORT), host: HOST }, () => done(null)));
    console.log(`visual-review: open ${origin}/#token=${token}`);
    // Keep running until the process is stopped.
    await new Promise(() => {});
    return 0;
}

async function notify(args) {
    const { values } = parseArgs({ args, options: { command: { type: "string" }, gap: { type: "string" } } });
    const text = values.command ?? process.env.VISUAL_REVIEW_NOTIFY;
    let command;
    try {
        command = JSON.parse(text ?? "null");
    } catch {
        command = null;
    }
    const gap = Number(values.gap ?? 10);
    if (
        !Array.isArray(command) ||
        command.length === 0 ||
        !command.every((a) => typeof a === "string") ||
        !(gap >= 0)
    ) {
        console.error(HELP.notify);
        return 2;
    }
    const { root, config } = await settings();
    const { notifyOnce } = await import("./lib/inbox.mjs");
    const stateDir = join(root, config.workDir, "state");
    console.log(`visual-review notify: watching ${join(stateDir, "inbox.json")}`);
    for (;;) {
        try {
            const sent = await notifyOnce({ stateDir, command, gap: gap * 60000 });
            if (sent.length > 0) {
                console.log(`visual-review notify: announced ${sent.map((r) => `#${r.pr}`).join(", ")}`);
            }
        } catch (err) {
            console.error(`visual-review notify: ${err.message}`);
        }
        await new Promise((done) => setTimeout(done, 30000));
    }
}

async function update(args) {
    const { positionals } = parseArgs({ args, allowPositionals: true });
    const pr = Number(positionals[0]);
    if (positionals.length !== 1 || !Number.isInteger(pr) || pr <= 0) {
        console.error(HELP.update);
        return 2;
    }
    const { root, config } = await settings();
    const { ghRunner } = await import("./lib/github.mjs");
    const { AcceptError, updateFromMaster } = await import("./lib/accept.mjs");
    const about = JSON.parse(await ghRunner(root)(["api", `repos/{owner}/{repo}/pulls/${pr}`]));
    if (about.state !== "open") {
        console.error(`visual-review update: #${pr} is ${about.state}, not open`);
        return 1;
    }
    try {
        const out = await updateFromMaster({
            repo: root,
            pr,
            branch: about.head.ref,
            config,
            progress: (step) => console.log(`visual-review update: ${step}`),
        });
        console.log(`visual-review update: pushed ${out.commit} to ${out.branch}`);
        for (const path of out.taken) {
            console.log(`  took ${config.defaultBranch}'s side: ${path}`);
        }
        console.log(
            out.recapture.length === 0
                ? "CI captures again; no baseline changed on the branch."
                : `CI captures again and compares these with their new baselines:\n${out.recapture.map((p) => `  ${p}`).join("\n")}`,
        );
        return 0;
    } catch (err) {
        if (err instanceof AcceptError) {
            console.error(`visual-review update: ${err.message}`);
            return 1;
        }
        throw err;
    }
}

async function compare(args) {
    const { values } = parseArgs({
        args,
        options: {
            baselines: { type: "string" },
            captures: { type: "string" },
            threshold: { type: "string" },
            "include-aa": { type: "boolean", default: false },
        },
    });
    const { classify, DEFAULT_THRESHOLD, readBaseline } = await import("./lib/compare.mjs");
    const threshold = Number(values.threshold ?? DEFAULT_THRESHOLD);
    if (!values.baselines || !values.captures || !(threshold >= 0 && threshold <= 1)) {
        console.error(HELP.compare);
        return 2;
    }
    const pngs = async (dir) => (await readdir(dir)).filter((f) => f.endsWith(".png"));
    const read = (dir, file, present) =>
        present.includes(file) ? (dir === values.baselines ? readBaseline : readFile)(join(dir, file)) : null;
    const [baselines, captures] = await Promise.all([pngs(values.baselines), pngs(values.captures)]);
    const counts = {};
    for (const file of [...new Set([...baselines, ...captures])].sort()) {
        const item = classify({
            baseline: await read(values.baselines, file, baselines),
            first: await read(values.captures, file, captures),
            threshold,
            includeAA: values["include-aa"],
        });
        counts[item.status] = (counts[item.status] ?? 0) + 1;
        if (item.status !== "unchanged") {
            console.log(JSON.stringify({ file, ...item }));
        }
    }
    console.log(JSON.stringify({ summary: counts }));
    return Object.keys(counts).some((status) => status !== "unchanged") ? 1 : 0;
}

async function gate(args) {
    const { runGate } = await import("./gate.mjs");
    return runGate(args);
}

async function init(args) {
    const { values } = parseArgs({ args, options: { force: { type: "boolean", default: false } } });
    const { repoRoot } = await import("./lib/config.mjs");
    const { init: run } = await import("./lib/init.mjs");
    const root = repoRoot();
    for (const line of run(root, { force: values.force })) {
        console.log(line);
    }
    return 0;
}

async function installBrowser() {
    const { createRequire } = await import("node:module");
    const { spawnSync } = await import("node:child_process");
    const { dirname } = await import("node:path");
    let pkg;
    try {
        pkg = createRequire(import.meta.url).resolve("playwright/package.json");
    } catch {
        console.error(
            "visual-review: playwright is not installed; add it to your devDependencies (npm i -D playwright)",
        );
        return 1;
    }
    const cli = join(dirname(pkg), JSON.parse(await readFile(pkg, "utf8")).bin.playwright);
    return spawnSync(process.execPath, [cli, "install", "--with-deps", "chromium"], { stdio: "inherit" }).status ?? 1;
}

const [name, ...rest] = process.argv.slice(2);
if (name === undefined || name === "--help" || name === "-h" || name === "help") {
    console.log(MAIN_HELP);
    process.exit(name === undefined ? 2 : 0);
}
if (name === "--version" || name === "-v") {
    console.log(JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8")).version);
    process.exit(0);
}
const run = Object.hasOwn(COMMANDS, name) ? COMMANDS[name] : undefined;
if (run === undefined) {
    console.error(`visual-review: unknown command "${name}"\n\n${MAIN_HELP}`);
    process.exit(2);
}
if (rest.includes("--help") || rest.includes("-h")) {
    const text = HELP[name] ?? (await import("./gate.mjs")).GATE_USAGE;
    console.log(text);
    process.exit(0);
}
try {
    process.exitCode = await run(rest);
} catch (err) {
    // A bad option, a missing config or a failed git call: say what, without a stack.
    if (err?.code?.startsWith?.("ERR_PARSE_ARGS") || /visual-review\.config\.json|git repository/.test(err?.message)) {
        console.error(`visual-review ${name}: ${err.message}`);
        process.exitCode = 2;
    } else {
        throw err;
    }
}
