import { describe, expect, it } from "vitest";

import { ALGORITHM_NAMES, LAYOUT_NAMES } from "../src/index.js";
import { GENERATORS } from "../src/samples.js";
import {
    ALGORITHM_GROUPS,
    GALLERY_PAGES,
    type GalleryPage,
    galleryTitle,
    GENERATOR_PRESETS,
    SIMULATION_LAYOUTS,
    STATIC_LAYOUTS,
    tileName,
} from "../stories/catalog.js";

// The Storybook demo offers what its catalog lists; these keep the catalog in step with what the extension registers,
// so a new layout, algorithm or generator cannot ship without a way to run it in the demo.
describe("the demo catalog", () => {
    it("lists every layout once", () => {
        expect([...SIMULATION_LAYOUTS, ...STATIC_LAYOUTS].sort()).toEqual([...LAYOUT_NAMES].sort());
    });

    it("lists every algorithm in exactly one group", () => {
        const listed = Object.values(ALGORITHM_GROUPS).flatMap((g) =>
            g.algorithms.map((a) => `graphty${a.charAt(0).toUpperCase()}${a.slice(1)}`),
        );
        expect(listed.sort()).toEqual([...ALGORITHM_NAMES].sort());
    });

    it("has a preset for every generator", () => {
        expect(Object.keys(GENERATOR_PRESETS).sort()).toEqual(Object.keys(GENERATORS).sort());
    });
});

/**
 * The story file of one gallery page: its Overview and one story per tile. Storybook reads story names and ids from
 * the source, so they cannot be made at run time; this writes them instead.
 * @param page - the page
 * @returns the file's text
 */
function galleryStories(page: GalleryPage): string {
    const stories = GALLERY_PAGES[page].map((key) => {
        const name = tileName(page, key);
        const id = name
            .split(/[^A-Za-z0-9]+/)
            .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
            .join("");
        return `export const ${id}: Story = {\n    ...tile("${page}", "${key}"),\n    name: "${name}",\n};\n`;
    });
    return [
        "// THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT stories/catalog.ts, then run",
        "// `npx vitest run test/demo-catalog.test.ts -u` (the test writes this file from the catalog).",
        'import type { Meta, StoryObj } from "@storybook/html-vite";',
        "",
        'import { overview, tile } from "../gallery-stories.js";',
        "",
        `const meta: Meta = { title: "${galleryTitle(page)}" };`,
        "export default meta;",
        "",
        "type Story = StoryObj;",
        "",
        `export const Overview: Story = overview("${page}");`,
        "",
        stories.join("\n"),
    ].join("\n");
}

// One story per gallery tile, in a folder per page: a catalog entry without its story fails here. After changing the
// catalog, `npx vitest run test/demo-catalog.test.ts -u` rewrites the story files.
describe("the gallery stories", () => {
    for (const page of Object.keys(GALLERY_PAGES) as GalleryPage[]) {
        it(`has the Overview and one story per tile of ${page}`, async () => {
            await expect(galleryStories(page)).toMatchFileSnapshot(`../stories/gallery/${page}.stories.ts`);
        });
    }
});
