// THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT stories/catalog.ts, then run
// `npx vitest run test/demo-catalog.test.ts -u` (the test writes this file from the catalog).
import type { Meta, StoryObj } from "@storybook/html-vite";

import { overview, tile } from "../gallery-stories.js";

const meta: Meta = { title: "Gallery/Centrality" };
export default meta;

type Story = StoryObj;

export const Overview: Story = overview("Centrality");

export const PageRank: Story = {
    ...tile("Centrality", "pageRank"),
    name: "PageRank",
};

export const PersonalizedPageRank: Story = {
    ...tile("Centrality", "personalizedPageRank"),
    name: "PersonalizedPageRank",
};

export const DeltaPageRank: Story = {
    ...tile("Centrality", "deltaPageRank"),
    name: "DeltaPageRank",
};

export const EigenvectorCentrality: Story = {
    ...tile("Centrality", "eigenvectorCentrality"),
    name: "EigenvectorCentrality",
};

export const KatzCentrality: Story = {
    ...tile("Centrality", "katzCentrality"),
    name: "KatzCentrality",
};

export const HITS: Story = {
    ...tile("Centrality", "hits"),
    name: "HITS",
};

export const ClosenessCentrality: Story = {
    ...tile("Centrality", "closenessCentrality"),
    name: "ClosenessCentrality",
};

export const NodeClosenessCentrality: Story = {
    ...tile("Centrality", "nodeClosenessCentrality"),
    name: "NodeClosenessCentrality",
};

export const BetweennessCentrality: Story = {
    ...tile("Centrality", "betweennessCentrality"),
    name: "BetweennessCentrality",
};

export const EdgeBetweennessCentrality: Story = {
    ...tile("Centrality", "edgeBetweennessCentrality"),
    name: "EdgeBetweennessCentrality",
};

export const DegreeCentrality: Story = {
    ...tile("Centrality", "degreeCentrality"),
    name: "DegreeCentrality",
};

export const Degrees: Story = {
    ...tile("Centrality", "degrees"),
    name: "Degrees",
};

export const KCoreDecomposition: Story = {
    ...tile("Centrality", "kCoreDecomposition"),
    name: "KCoreDecomposition",
};

export const TriangleCount: Story = {
    ...tile("Centrality", "triangleCount"),
    name: "TriangleCount",
};
