// THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT stories/catalog.ts, then run
// `npx vitest run test/demo-catalog.test.ts -u` (the test writes this file from the catalog).
import type { Meta, StoryObj } from "@storybook/html-vite";

import { overview, tile } from "../gallery-stories.js";

const meta: Meta = { title: "Gallery/Communities" };
export default meta;

type Story = StoryObj;

export const Overview: Story = overview("Communities");

export const Louvain: Story = {
    ...tile("Communities", "louvain"),
    name: "Louvain",
};

export const Leiden: Story = {
    ...tile("Communities", "leiden"),
    name: "Leiden",
};

export const LabelPropagation: Story = {
    ...tile("Communities", "labelPropagation"),
    name: "LabelPropagation",
};

export const LabelPropagationSynchronous: Story = {
    ...tile("Communities", "labelPropagationSynchronous"),
    name: "LabelPropagationSynchronous",
};

export const LabelPropagationSemiSupervised: Story = {
    ...tile("Communities", "labelPropagationSemiSupervised"),
    name: "LabelPropagationSemiSupervised",
};

export const GirvanNewman: Story = {
    ...tile("Communities", "girvanNewman"),
    name: "GirvanNewman",
};

export const MarkovClustering: Story = {
    ...tile("Communities", "markovClustering"),
    name: "MarkovClustering",
};

export const SpectralClustering: Story = {
    ...tile("Communities", "spectralClustering"),
    name: "SpectralClustering",
};

export const HierarchicalClustering: Story = {
    ...tile("Communities", "hierarchicalClustering"),
    name: "HierarchicalClustering",
};

export const TeraHAC: Story = {
    ...tile("Communities", "teraHAC"),
    name: "TeraHAC",
};

export const Grsbm: Story = {
    ...tile("Communities", "grsbm"),
    name: "Grsbm",
};

export const SyncClustering: Story = {
    ...tile("Communities", "syncClustering"),
    name: "SyncClustering",
};

export const Modularity: Story = {
    ...tile("Communities", "modularity"),
    name: "Modularity",
};

export const ConnectedComponents: Story = {
    ...tile("Communities", "connectedComponents"),
    name: "ConnectedComponents",
};
