// THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT stories/catalog.ts, then run
// `npx vitest run test/demo-catalog.test.ts -u` (the test writes this file from the catalog).
import type { Meta, StoryObj } from "@storybook/html-vite";

import { overview, tile } from "../gallery-stories.js";

const meta: Meta = { title: "Gallery/Flows And Cuts" };
export default meta;

type Story = StoryObj;

export const Overview: Story = overview("FlowsAndCuts");

export const MaxFlow: Story = {
    ...tile("FlowsAndCuts", "maxFlow"),
    name: "MaxFlow",
};

export const MinSTCut: Story = {
    ...tile("FlowsAndCuts", "minSTCut"),
    name: "MinSTCut",
};

export const StoerWagner: Story = {
    ...tile("FlowsAndCuts", "stoerWagner"),
    name: "StoerWagner",
};

export const KargerMinCut: Story = {
    ...tile("FlowsAndCuts", "kargerMinCut"),
    name: "KargerMinCut",
};
