// THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT stories/catalog.ts, then run
// `npx vitest run test/demo-catalog.test.ts -u` (the test writes this file from the catalog).
import type { Meta, StoryObj } from "@storybook/html-vite";

import { overview, tile } from "../gallery-stories.js";

const meta: Meta = { title: "Gallery/Formats" };
export default meta;

type Story = StoryObj;

export const Overview: Story = overview("Formats");

export const Graphml: Story = {
    ...tile("Formats", "graphml"),
    name: "graphml",
};

export const Gexf: Story = {
    ...tile("Formats", "gexf"),
    name: "gexf",
};

export const Gml: Story = {
    ...tile("Formats", "gml"),
    name: "gml",
};

export const Dot: Story = {
    ...tile("Formats", "dot"),
    name: "dot",
};

export const Pajek: Story = {
    ...tile("Formats", "pajek"),
    name: "pajek",
};

export const Csv: Story = {
    ...tile("Formats", "csv"),
    name: "csv",
};

export const Json: Story = {
    ...tile("Formats", "json"),
    name: "json",
};

export const Neo4j: Story = {
    ...tile("Formats", "neo4j"),
    name: "neo4j",
};

export const Xgmml: Story = {
    ...tile("Formats", "xgmml"),
    name: "xgmml",
};

export const Cx2: Story = {
    ...tile("Formats", "cx2"),
    name: "cx2",
};

export const Cx: Story = {
    ...tile("Formats", "cx"),
    name: "cx",
};

export const Obo: Story = {
    ...tile("Formats", "obo"),
    name: "obo",
};

export const Cys: Story = {
    ...tile("Formats", "cys"),
    name: "cys",
};

export const Auto: Story = {
    ...tile("Formats", "auto"),
    name: "auto",
};

export const Export: Story = {
    ...tile("Formats", "export"),
    name: "export",
};
