// THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT stories/catalog.ts, then run
// `npx vitest run test/demo-catalog.test.ts -u` (the test writes this file from the catalog).
import type { Meta, StoryObj } from "@storybook/html-vite";

import { overview, tile } from "../gallery-stories.js";

const meta: Meta = { title: "Gallery/Generators" };
export default meta;

type Story = StoryObj;

export const Overview: Story = overview("Generators");

export const Ak: Story = {
    ...tile("Generators", "ak"),
    name: "ak",
};

export const BalancedTree: Story = {
    ...tile("Generators", "balanced-tree"),
    name: "balanced-tree",
};

export const BarabasiAlbert: Story = {
    ...tile("Generators", "barabasi-albert"),
    name: "barabasi-albert",
};

export const Barbell: Story = {
    ...tile("Generators", "barbell"),
    name: "barbell",
};

export const BianconiBarabasi: Story = {
    ...tile("Generators", "bianconi-barabasi"),
    name: "bianconi-barabasi",
};

export const BipartiteConfigurationModel: Story = {
    ...tile("Generators", "bipartite-configuration-model"),
    name: "bipartite-configuration-model",
};

export const Caveman: Story = {
    ...tile("Generators", "caveman"),
    name: "caveman",
};

export const ChungLu: Story = {
    ...tile("Generators", "chung-lu"),
    name: "chung-lu",
};

export const CircularLadder: Story = {
    ...tile("Generators", "circular-ladder"),
    name: "circular-ladder",
};

export const Complete: Story = {
    ...tile("Generators", "complete"),
    name: "complete",
};

export const CompleteBipartite: Story = {
    ...tile("Generators", "complete-bipartite"),
    name: "complete-bipartite",
};

export const CompleteMultipartite: Story = {
    ...tile("Generators", "complete-multipartite"),
    name: "complete-multipartite",
};

export const ConfigurationModel: Story = {
    ...tile("Generators", "configuration-model"),
    name: "configuration-model",
};

export const ConnectedCaveman: Story = {
    ...tile("Generators", "connected-caveman"),
    name: "connected-caveman",
};

export const Cycle: Story = {
    ...tile("Generators", "cycle"),
    name: "cycle",
};

export const DegreeCorrectedSbm: Story = {
    ...tile("Generators", "degree-corrected-sbm"),
    name: "degree-corrected-sbm",
};

export const DirectedConfigurationModel: Story = {
    ...tile("Generators", "directed-configuration-model"),
    name: "directed-configuration-model",
};

export const DuplicationDivergence: Story = {
    ...tile("Generators", "duplication-divergence"),
    name: "duplication-divergence",
};

export const Empty: Story = {
    ...tile("Generators", "empty"),
    name: "empty",
};

export const ErdosRenyi: Story = {
    ...tile("Generators", "erdos-renyi"),
    name: "erdos-renyi",
};

export const ErdosRenyiGnm: Story = {
    ...tile("Generators", "erdos-renyi-gnm"),
    name: "erdos-renyi-gnm",
};

export const ForestFire: Story = {
    ...tile("Generators", "forest-fire"),
    name: "forest-fire",
};

export const Genrmf: Story = {
    ...tile("Generators", "genrmf"),
    name: "genrmf",
};

export const Grid: Story = {
    ...tile("Generators", "grid"),
    name: "grid",
};

export const Grid3d: Story = {
    ...tile("Generators", "grid-3d"),
    name: "grid-3d",
};

export const GridFlowNetwork: Story = {
    ...tile("Generators", "grid-flow-network"),
    name: "grid-flow-network",
};

export const HexagonalLattice: Story = {
    ...tile("Generators", "hexagonal-lattice"),
    name: "hexagonal-lattice",
};

export const Hyperbolic: Story = {
    ...tile("Generators", "hyperbolic"),
    name: "hyperbolic",
};

export const Hypercube: Story = {
    ...tile("Generators", "hypercube"),
    name: "hypercube",
};

export const Knn: Story = {
    ...tile("Generators", "knn"),
    name: "knn",
};

export const Kronecker: Story = {
    ...tile("Generators", "kronecker"),
    name: "kronecker",
};

export const Ladder: Story = {
    ...tile("Generators", "ladder"),
    name: "ladder",
};

export const LayeredFlowNetwork: Story = {
    ...tile("Generators", "layered-flow-network"),
    name: "layered-flow-network",
};

export const Lfr: Story = {
    ...tile("Generators", "lfr"),
    name: "lfr",
};

export const Lollipop: Story = {
    ...tile("Generators", "lollipop"),
    name: "lollipop",
};

export const MobiusLadder: Story = {
    ...tile("Generators", "mobius-ladder"),
    name: "mobius-ladder",
};

export const Named: Story = {
    ...tile("Generators", "named"),
    name: "named",
};

export const NewmanWatts: Story = {
    ...tile("Generators", "newman-watts"),
    name: "newman-watts",
};

export const Path: Story = {
    ...tile("Generators", "path"),
    name: "path",
};

export const Petersen: Story = {
    ...tile("Generators", "petersen"),
    name: "petersen",
};

export const PlantedPartition: Story = {
    ...tile("Generators", "planted-partition"),
    name: "planted-partition",
};

export const Price: Story = {
    ...tile("Generators", "price"),
    name: "price",
};

export const RandomApollonian: Story = {
    ...tile("Generators", "random-apollonian"),
    name: "random-apollonian",
};

export const RandomBipartite: Story = {
    ...tile("Generators", "random-bipartite"),
    name: "random-bipartite",
};

export const RandomDag: Story = {
    ...tile("Generators", "random-dag"),
    name: "random-dag",
};

export const RandomGeometric: Story = {
    ...tile("Generators", "random-geometric"),
    name: "random-geometric",
};

export const RandomOrderDag: Story = {
    ...tile("Generators", "random-order-dag"),
    name: "random-order-dag",
};

export const RandomRecursiveTree: Story = {
    ...tile("Generators", "random-recursive-tree"),
    name: "random-recursive-tree",
};

export const RandomRegular: Story = {
    ...tile("Generators", "random-regular"),
    name: "random-regular",
};

export const RandomTree: Story = {
    ...tile("Generators", "random-tree"),
    name: "random-tree",
};

export const RingOfCliques: Story = {
    ...tile("Generators", "ring-of-cliques"),
    name: "ring-of-cliques",
};

export const Rmat: Story = {
    ...tile("Generators", "rmat"),
    name: "rmat",
};

export const Star: Story = {
    ...tile("Generators", "star"),
    name: "star",
};

export const StochasticBlockModel: Story = {
    ...tile("Generators", "stochastic-block-model"),
    name: "stochastic-block-model",
};

export const TriangularLattice: Story = {
    ...tile("Generators", "triangular-lattice"),
    name: "triangular-lattice",
};

export const WattsStrogatz: Story = {
    ...tile("Generators", "watts-strogatz"),
    name: "watts-strogatz",
};

export const Waxman: Story = {
    ...tile("Generators", "waxman"),
    name: "waxman",
};

export const Wheel: Story = {
    ...tile("Generators", "wheel"),
    name: "wheel",
};

export const WilsonMaze: Story = {
    ...tile("Generators", "wilson-maze"),
    name: "wilson-maze",
};
