// THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT stories/catalog.ts, then run
// `npx vitest run test/demo-catalog.test.ts -u` (the test writes this file from the catalog).
import type { Meta, StoryObj } from "@storybook/html-vite";

import { overview, tile } from "../gallery-stories.js";

const meta: Meta = { title: "Gallery/Layouts" };
export default meta;

type Story = StoryObj;

export const Overview: Story = overview("Layouts");

export const ForceAtlas2: Story = {
    ...tile("Layouts", "forceatlas2"),
    name: "ForceAtlas2",
};

export const FruchtermanReingold: Story = {
    ...tile("Layouts", "fruchterman-reingold"),
    name: "Fruchterman-Reingold",
};

export const SpringElectrical: Story = {
    ...tile("Layouts", "spring-electrical"),
    name: "Spring-Electrical",
};

export const Random: Story = {
    ...tile("Layouts", "random"),
    name: "Random",
};

export const Circular: Story = {
    ...tile("Layouts", "circular"),
    name: "Circular",
};

export const Spiral: Story = {
    ...tile("Layouts", "spiral"),
    name: "Spiral",
};

export const Grid: Story = {
    ...tile("Layouts", "grid"),
    name: "Grid",
};

export const Shell: Story = {
    ...tile("Layouts", "shell"),
    name: "Shell",
};

export const Bipartite: Story = {
    ...tile("Layouts", "bipartite"),
    name: "Bipartite",
};

export const Multipartite: Story = {
    ...tile("Layouts", "multipartite"),
    name: "Multipartite",
};

export const BFS: Story = {
    ...tile("Layouts", "bfs"),
    name: "BFS",
};

export const Radial: Story = {
    ...tile("Layouts", "radial"),
    name: "Radial",
};

export const Planar: Story = {
    ...tile("Layouts", "planar"),
    name: "Planar",
};

export const Spectral: Story = {
    ...tile("Layouts", "spectral"),
    name: "Spectral",
};

export const KamadaKawai: Story = {
    ...tile("Layouts", "kamada-kawai"),
    name: "Kamada-Kawai",
};

export const ARF: Story = {
    ...tile("Layouts", "arf"),
    name: "ARF",
};
