// THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT stories/catalog.ts, then run
// `npx vitest run test/demo-catalog.test.ts -u` (the test writes this file from the catalog).
import type { Meta, StoryObj } from "@storybook/html-vite";

import { overview, tile } from "../gallery-stories.js";

const meta: Meta = { title: "Gallery/Link Prediction" };
export default meta;

type Story = StoryObj;

export const Overview: Story = overview("LinkPrediction");

export const CommonNeighborsScore: Story = {
    ...tile("LinkPrediction", "commonNeighborsScore"),
    name: "CommonNeighborsScore",
};

export const AdamicAdarScore: Story = {
    ...tile("LinkPrediction", "adamicAdarScore"),
    name: "AdamicAdarScore",
};

export const CommonNeighborsForPairs: Story = {
    ...tile("LinkPrediction", "commonNeighborsForPairs"),
    name: "CommonNeighborsForPairs",
};

export const AdamicAdarForPairs: Story = {
    ...tile("LinkPrediction", "adamicAdarForPairs"),
    name: "AdamicAdarForPairs",
};

export const CommonNeighborsPrediction: Story = {
    ...tile("LinkPrediction", "commonNeighborsPrediction"),
    name: "CommonNeighborsPrediction",
};

export const AdamicAdarPrediction: Story = {
    ...tile("LinkPrediction", "adamicAdarPrediction"),
    name: "AdamicAdarPrediction",
};

export const TopCandidatesForNode: Story = {
    ...tile("LinkPrediction", "topCandidatesForNode"),
    name: "TopCandidatesForNode",
};

export const TopAdamicAdarCandidatesForNode: Story = {
    ...tile("LinkPrediction", "topAdamicAdarCandidatesForNode"),
    name: "TopAdamicAdarCandidatesForNode",
};

export const EvaluateCommonNeighbors: Story = {
    ...tile("LinkPrediction", "evaluateCommonNeighbors"),
    name: "EvaluateCommonNeighbors",
};

export const EvaluateAdamicAdar: Story = {
    ...tile("LinkPrediction", "evaluateAdamicAdar"),
    name: "EvaluateAdamicAdar",
};

export const CompareAdamicAdarWithCommonNeighbors: Story = {
    ...tile("LinkPrediction", "compareAdamicAdarWithCommonNeighbors"),
    name: "CompareAdamicAdarWithCommonNeighbors",
};
