// THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT stories/catalog.ts, then run
// `npx vitest run test/demo-catalog.test.ts -u` (the test writes this file from the catalog).
import type { Meta, StoryObj } from "@storybook/html-vite";

import { overview, tile } from "../gallery-stories.js";

const meta: Meta = { title: "Gallery/Paths And Trees" };
export default meta;

type Story = StoryObj;

export const Overview: Story = overview("PathsAndTrees");

export const Dijkstra: Story = {
    ...tile("PathsAndTrees", "dijkstra"),
    name: "Dijkstra",
};

export const BellmanFord: Story = {
    ...tile("PathsAndTrees", "bellmanFord"),
    name: "BellmanFord",
};

export const BidirectionalDijkstra: Story = {
    ...tile("PathsAndTrees", "bidirectionalDijkstra"),
    name: "BidirectionalDijkstra",
};

export const AStar: Story = {
    ...tile("PathsAndTrees", "aStar"),
    name: "AStar",
};

export const AllPairsShortestPath: Story = {
    ...tile("PathsAndTrees", "allPairsShortestPath"),
    name: "AllPairsShortestPath",
};

export const BreadthFirstSearch: Story = {
    ...tile("PathsAndTrees", "breadthFirstSearch"),
    name: "BreadthFirstSearch",
};

export const DirectionOptimizedBfs: Story = {
    ...tile("PathsAndTrees", "directionOptimizedBfs"),
    name: "DirectionOptimizedBfs",
};

export const DepthFirstSearch: Story = {
    ...tile("PathsAndTrees", "depthFirstSearch"),
    name: "DepthFirstSearch",
};

export const KruskalMST: Story = {
    ...tile("PathsAndTrees", "kruskalMST"),
    name: "KruskalMST",
};

export const PrimMST: Story = {
    ...tile("PathsAndTrees", "primMST"),
    name: "PrimMST",
};
