// THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT stories/catalog.ts, then run
// `npx vitest run test/demo-catalog.test.ts -u` (the test writes this file from the catalog).
import type { Meta, StoryObj } from "@storybook/html-vite";

import { overview, tile } from "../gallery-stories.js";

const meta: Meta = { title: "Gallery/Structure" };
export default meta;

type Story = StoryObj;

export const Overview: Story = overview("Structure");

export const WeaklyConnectedComponents: Story = {
    ...tile("Structure", "weaklyConnectedComponents"),
    name: "WeaklyConnectedComponents",
};

export const StronglyConnectedComponents: Story = {
    ...tile("Structure", "stronglyConnectedComponents"),
    name: "StronglyConnectedComponents",
};

export const Condensation: Story = {
    ...tile("Structure", "condensation"),
    name: "Condensation",
};

export const HasCycle: Story = {
    ...tile("Structure", "hasCycle"),
    name: "HasCycle",
};

export const TopologicalSort: Story = {
    ...tile("Structure", "topologicalSort"),
    name: "TopologicalSort",
};

export const IsBipartite: Story = {
    ...tile("Structure", "isBipartite"),
    name: "IsBipartite",
};

export const MaximumBipartiteMatching: Story = {
    ...tile("Structure", "maximumBipartiteMatching"),
    name: "MaximumBipartiteMatching",
};

export const GreedyBipartiteMatching: Story = {
    ...tile("Structure", "greedyBipartiteMatching"),
    name: "GreedyBipartiteMatching",
};

export const IsGraphIsomorphic: Story = {
    ...tile("Structure", "isGraphIsomorphic"),
    name: "IsGraphIsomorphic",
};

export const FindAllIsomorphisms: Story = {
    ...tile("Structure", "findAllIsomorphisms"),
    name: "FindAllIsomorphisms",
};
