/**
 * THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT tmp/css-baselines.json
 *
 * CSS Baseline Verification Tests
 *
 * These tests verify that CSS properties match the recorded baselines.
 * Run these tests after any refactoring to ensure styles haven't changed.
 *
 * Tests cover:
 * - CSS variables (--input-size, --button-height, etc.)
 * - Computed styles (padding, borderRadius, backgroundColor, fontSize, etc.)
 */
import {
    MantineProvider,
    // Input components
    TextInput,
    NumberInput,
    Select,
    Textarea,
    PasswordInput,
    Autocomplete,
    MultiSelect,
    TagsInput,
    PillsInput,
    FileInput,
    JsonInput,
    InputClearButton,
    // Button components
    Button,
    ActionIcon,
    CloseButton,
    // Control components
    Switch,
    Checkbox,
    Radio,
    Slider,
    RangeSlider,
    SegmentedControl,
    // Display components
    Text,
    Badge,
    Pill,
    Avatar,
    ThemeIcon,
    Indicator,
    Kbd,
    // Feedback components
    Loader,
    Progress,
    RingProgress,
    // Navigation components
    Anchor,
    Burger,
    Pagination,
    Stepper,
} from "@mantine/core";
import { render } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import { compactTheme } from "../../src";
import { displayComponentExtensions } from "../../src/theme/components/display";

// Simple icon placeholder for tests
const IconPlaceholder = () => <span style={{ width: 14, height: 14 }}>★</span>;

/**
 * Expected CSS variable values for compact inputs.
 * These values were captured from the original implementation.
 */
const EXPECTED_CSS_VARS = {
    "--input-size": "24px",
    "--input-fz": "11px",
    "--input-bg": "#2a3035",
    "--input-bd": "none",
};

/**
 * Helper to extract CSS variables from an element's computed style.
 */
function getCssVars(element: Element | null): Record<string, string> {
    if (!element) return {};
    const style = getComputedStyle(element);
    return {
        "--input-size": style.getPropertyValue("--input-size").trim(),
        "--input-fz": style.getPropertyValue("--input-fz").trim(),
        "--input-bg": style.getPropertyValue("--input-bg").trim(),
        "--input-bd": style.getPropertyValue("--input-bd").trim(),
    };
}

/**
 * Helper to extract a specific CSS variable from an element.
 */
function getCssVar(element: Element | null, varName: string): string {
    if (!element) return "";
    return getComputedStyle(element).getPropertyValue(varName).trim();
}

/**
 * Helper to extract computed style properties from an element.
 */
function getComputedStyles(element: Element | null, properties: string[]): Record<string, string> {
    if (!element) return {};
    const style = getComputedStyle(element);
    const result: Record<string, string> = {};
    for (const prop of properties) {
        result[prop] = style.getPropertyValue(prop);
    }
    return result;
}

/**
 * Helper to render a component with the compact theme.
 */
function renderWithTheme(ui: React.ReactElement) {
    return render(<MantineProvider theme={compactTheme}>{ui}</MantineProvider>);
}

describe("CSS Baseline Verification", () => {
    /**
     * Phase 2 Refactor: Components now use defaultProps { size: "sm" } instead of size="compact".
     * Tests verify that default rendering produces the same visual output.
     * No explicit size prop is passed - we rely on defaultProps.
     */

    describe("TextInput CSS Variables", () => {
        it("has correct CSS variables on wrapper", () => {
            const { container } = renderWithTheme(<TextInput label="Test" />);
            const wrapper = container.querySelector(".mantine-TextInput-wrapper");
            const cssVars = getCssVars(wrapper);

            expect(cssVars["--input-size"]).toBe(EXPECTED_CSS_VARS["--input-size"]);
            expect(cssVars["--input-fz"]).toBe(EXPECTED_CSS_VARS["--input-fz"]);
        });
    });

    describe("NumberInput CSS Variables", () => {
        it("has correct CSS variables on wrapper", () => {
            const { container } = renderWithTheme(<NumberInput label="Test" />);
            const wrapper = container.querySelector(".mantine-NumberInput-wrapper");
            const cssVars = getCssVars(wrapper);

            expect(cssVars["--input-size"]).toBe(EXPECTED_CSS_VARS["--input-size"]);
            expect(cssVars["--input-fz"]).toBe(EXPECTED_CSS_VARS["--input-fz"]);
        });

        it("has --input-right-section-width set", () => {
            const { container } = renderWithTheme(<NumberInput label="Test" />);
            const wrapper = container.querySelector(".mantine-NumberInput-wrapper");
            const style = wrapper ? getComputedStyle(wrapper) : null;
            const rightSectionWidth = style?.getPropertyValue("--input-right-section-width").trim();

            expect(rightSectionWidth).toBe("24px");
        });
    });

    describe("Select CSS Variables", () => {
        it("has correct CSS variables on wrapper", () => {
            const { container } = renderWithTheme(<Select label="Test" data={["A", "B"]} />);
            const wrapper = container.querySelector(".mantine-Select-wrapper");
            const cssVars = getCssVars(wrapper);

            expect(cssVars["--input-size"]).toBe(EXPECTED_CSS_VARS["--input-size"]);
            expect(cssVars["--input-fz"]).toBe(EXPECTED_CSS_VARS["--input-fz"]);
        });
    });

    describe("Textarea CSS Variables", () => {
        it("has correct CSS variables on wrapper (no fixed height)", () => {
            const { container } = renderWithTheme(<Textarea label="Test" />);
            const wrapper = container.querySelector(".mantine-Textarea-wrapper");
            const cssVars = getCssVars(wrapper);

            // Textarea doesn't set --input-size (uses auto height)
            // In JSDOM, this returns empty; in browser, it resolves to computed value
            expect(cssVars["--input-fz"]).toBe(EXPECTED_CSS_VARS["--input-fz"]);
        });
    });

    describe("PasswordInput CSS Variables", () => {
        it("has correct CSS variables on wrapper", () => {
            const { container } = renderWithTheme(<PasswordInput label="Test" />);
            const wrapper = container.querySelector(".mantine-PasswordInput-wrapper");
            const cssVars = getCssVars(wrapper);

            expect(cssVars["--input-size"]).toBe(EXPECTED_CSS_VARS["--input-size"]);
            expect(cssVars["--input-fz"]).toBe(EXPECTED_CSS_VARS["--input-fz"]);
        });
    });

    describe("Autocomplete CSS Variables", () => {
        it("has correct CSS variables on wrapper", () => {
            const { container } = renderWithTheme(<Autocomplete label="Test" data={["A", "B"]} />);
            const wrapper = container.querySelector(".mantine-Autocomplete-wrapper");
            const cssVars = getCssVars(wrapper);

            expect(cssVars["--input-size"]).toBe(EXPECTED_CSS_VARS["--input-size"]);
            expect(cssVars["--input-fz"]).toBe(EXPECTED_CSS_VARS["--input-fz"]);
        });
    });

    describe("MultiSelect CSS Variables", () => {
        it("has correct CSS variables on wrapper", () => {
            const { container } = renderWithTheme(<MultiSelect label="Test" data={["A", "B"]} />);
            const wrapper = container.querySelector(".mantine-MultiSelect-wrapper");
            const cssVars = getCssVars(wrapper);

            expect(cssVars["--input-size"]).toBe(EXPECTED_CSS_VARS["--input-size"]);
            expect(cssVars["--input-fz"]).toBe(EXPECTED_CSS_VARS["--input-fz"]);
        });

        it("has --combobox-chevron-size set", () => {
            const { container } = renderWithTheme(<MultiSelect label="Test" data={["A", "B"]} />);
            const wrapper = container.querySelector(".mantine-MultiSelect-wrapper");
            const style = wrapper ? getComputedStyle(wrapper) : null;
            const chevronSize = style?.getPropertyValue("--combobox-chevron-size").trim();

            expect(chevronSize).toBe("12px");
        });
    });

    describe("TagsInput CSS Variables", () => {
        it("has correct CSS variables on wrapper (no fixed height)", () => {
            const { container } = renderWithTheme(<TagsInput label="Test" data={["A", "B"]} />);
            const wrapper = container.querySelector(".mantine-TagsInput-wrapper");
            const cssVars = getCssVars(wrapper);

            // TagsInput doesn't set --input-size (uses auto height)
            expect(cssVars["--input-fz"]).toBe(EXPECTED_CSS_VARS["--input-fz"]);
        });
    });

    describe("PillsInput CSS Variables", () => {
        it("has correct CSS variables on wrapper (no fixed height)", () => {
            const { container } = renderWithTheme(
                <PillsInput label="Test">
                    <PillsInput.Field placeholder="Enter" />
                </PillsInput>
            );
            const wrapper = container.querySelector(".mantine-PillsInput-wrapper");
            const cssVars = getCssVars(wrapper);

            // PillsInput doesn't set --input-size (uses auto height)
            expect(cssVars["--input-fz"]).toBe(EXPECTED_CSS_VARS["--input-fz"]);
        });
    });

    describe("FileInput CSS Variables", () => {
        it("has correct CSS variables on wrapper", () => {
            const { container } = renderWithTheme(<FileInput label="Test" />);
            const wrapper = container.querySelector(".mantine-FileInput-wrapper");
            const cssVars = getCssVars(wrapper);

            expect(cssVars["--input-size"]).toBe(EXPECTED_CSS_VARS["--input-size"]);
            expect(cssVars["--input-fz"]).toBe(EXPECTED_CSS_VARS["--input-fz"]);
        });
    });

    describe("JsonInput CSS Variables", () => {
        it("has correct CSS variables on wrapper (no fixed height)", () => {
            const { container } = renderWithTheme(<JsonInput label="Test" />);
            const wrapper = container.querySelector(".mantine-JsonInput-wrapper");
            const cssVars = getCssVars(wrapper);

            // JsonInput doesn't set --input-size (uses auto height)
            expect(cssVars["--input-fz"]).toBe(EXPECTED_CSS_VARS["--input-fz"]);
        });
    });

    describe("InputClearButton CSS Variables", () => {
        it("has correct CSS variables on root", () => {
            const { container } = renderWithTheme(<InputClearButton aria-label="Clear" />);
            const root = container.querySelector(".mantine-InputClearButton-root");
            const style = root ? getComputedStyle(root) : null;

            expect(style?.getPropertyValue("--cb-size").trim()).toBe("16px");
            expect(style?.getPropertyValue("--cb-icon-size").trim()).toBe("12px");
        });
    });

    /**
     * Note: Computed style tests (padding, borderRadius, fontSize) require browser-based testing.
     * JSDOM doesn't apply CSS stylesheets, so computed styles return empty strings.
     * Use Storybook visual tests or Playwright for computed style verification.
     *
     * The CSS variable tests above verify that the theme extensions correctly set
     * the CSS custom properties that drive the computed styles in real browsers.
     */
});

/**
 * Button Component Baseline Verification Tests
 *
 * Tests CSS variables set by theme extensions:
 * - Button: --button-height: 24px, --button-fz: 11px, --button-padding-x: 8px
 * - ActionIcon: --ai-size: 24px
 * - CloseButton: --cb-size: 16px, --cb-icon-size: 12px
 */
describe("Button Component CSS Baseline Verification", () => {
    describe("Button with default size (sm)", () => {
        it("has correct CSS variables on root", () => {
            const { container } = renderWithTheme(<Button>Click</Button>);
            const root = container.querySelector(".mantine-Button-root");

            expect(getCssVar(root, "--button-height")).toBe("24px");
            expect(getCssVar(root, "--button-fz")).toBe("11px");
            expect(getCssVar(root, "--button-padding-x")).toBe("8px");
        });
    });

    describe("ActionIcon with default size (sm)", () => {
        it("has correct CSS variables on root", () => {
            const { container } = renderWithTheme(
                <ActionIcon aria-label="Action">
                    <IconPlaceholder />
                </ActionIcon>
            );
            const root = container.querySelector(".mantine-ActionIcon-root");

            expect(getCssVar(root, "--ai-size")).toBe("24px");
        });
    });

    describe("CloseButton (defaults to xs)", () => {
        it("has correct CSS variables on root", () => {
            const { container } = renderWithTheme(<CloseButton aria-label="Close" />);
            const root = container.querySelector(".mantine-CloseButton-root");

            expect(getCssVar(root, "--cb-size")).toBe("16px");
            expect(getCssVar(root, "--cb-icon-size")).toBe("12px");
        });
    });
});

/**
 * Control Component Baseline Verification Tests
 *
 * Tests CSS variables set by theme extensions:
 * - Switch: --switch-height: 16px, --switch-width: 28px, --switch-thumb-size: 12px
 * - Checkbox: --checkbox-size: 16px
 * - Radio: --radio-size: 16px, --radio-icon-size: 6px
 * - Slider: --slider-size: 4px, --slider-thumb-size: 12px
 * - SegmentedControl: --sc-font-size: 10px, --sc-padding: 4px 8px
 */
describe("Control Component CSS Baseline Verification", () => {
    describe("Switch with default size (sm)", () => {
        it("has correct CSS variables on root", () => {
            const { container } = renderWithTheme(<Switch label="Toggle" />);
            const root = container.querySelector(".mantine-Switch-root");

            expect(getCssVar(root, "--switch-height")).toBe("16px");
            expect(getCssVar(root, "--switch-width")).toBe("28px");
            expect(getCssVar(root, "--switch-thumb-size")).toBe("12px");
        });
    });

    describe("Checkbox with default size (sm)", () => {
        it("has correct CSS variables on root", () => {
            const { container } = renderWithTheme(<Checkbox label="Check" />);
            const root = container.querySelector(".mantine-Checkbox-root");

            expect(getCssVar(root, "--checkbox-size")).toBe("16px");
        });
    });

    describe("Radio with default size (sm)", () => {
        it("has correct CSS variables on root", () => {
            const { container } = renderWithTheme(<Radio label="Option" value="a" />);
            const root = container.querySelector(".mantine-Radio-root");

            expect(getCssVar(root, "--radio-size")).toBe("16px");
            expect(getCssVar(root, "--radio-icon-size")).toBe("6px");
        });
    });

    describe("Slider with default size (sm)", () => {
        it("has correct CSS variables on root", () => {
            const { container } = renderWithTheme(<Slider defaultValue={50} />);
            const root = container.querySelector(".mantine-Slider-root");

            expect(getCssVar(root, "--slider-size")).toBe("4px");
            expect(getCssVar(root, "--slider-thumb-size")).toBe("12px");
        });
    });

    describe("RangeSlider with default size (sm)", () => {
        it("has correct CSS variables on root", () => {
            const { container } = renderWithTheme(<RangeSlider defaultValue={[20, 80]} />);
            const root = container.querySelector(".mantine-Slider-root"); // Note: uses Slider classes

            expect(getCssVar(root, "--slider-size")).toBe("4px");
            expect(getCssVar(root, "--slider-thumb-size")).toBe("12px");
        });
    });

    describe("SegmentedControl with default size (sm)", () => {
        it("has correct CSS variables on root", () => {
            const { container } = renderWithTheme(
                <SegmentedControl data={["A", "B", "C"]} />
            );
            const root = container.querySelector(".mantine-SegmentedControl-root");

            expect(getCssVar(root, "--sc-font-size")).toBe("10px");
            expect(getCssVar(root, "--sc-padding")).toBe("4px 8px");
        });
    });
});

/**
 * Display Component Baseline Verification Tests
 *
 * Tests CSS variables set by theme extensions:
 * - Text: Uses global fontSizes from theme (no component-level vars)
 * - Badge: --badge-height: 14px, --badge-fz: 9px, --badge-padding-x: 4px
 * - Pill: --pill-height: 16px, --pill-fz: 10px
 * - Avatar: --avatar-size: 24px
 * - ThemeIcon: --ti-size: 24px
 * - Indicator: --indicator-size: 8px
 * - Kbd: --kbd-fz: 10px, --kbd-padding: 2px 4px
 */
describe("Display Component CSS Baseline Verification", () => {
    describe("Text extension", () => {
        it("does not set component-level vars (uses global fontSizes)", () => {
            // Text no longer uses component-level vars. It uses the theme's
            // global fontSizes (compactFontSizes) which sets sm to 11px.
            // This test verifies the extension configuration, not computed styles.
            expect(displayComponentExtensions.Text.vars).toBeUndefined();
        });

        it("does not set default size (uses global fontSizes)", () => {
            expect(displayComponentExtensions.Text.defaultProps?.size).toBeUndefined();
        });
    });

    describe("Badge (defaults to compact)", () => {
        it("has correct CSS variables on root by default", () => {
            // After refactor, compact styling is applied by default
            const { container } = renderWithTheme(<Badge>Label</Badge>);
            const root = container.querySelector(".mantine-Badge-root");

            expect(getCssVar(root, "--badge-height")).toBe("14px");
            expect(getCssVar(root, "--badge-fz")).toBe("9px");
            expect(getCssVar(root, "--badge-padding-x")).toBe("4px");
        });
    });

    describe("Pill (defaults to compact)", () => {
        it("has correct CSS variables on root by default", () => {
            // After refactor, compact styling is applied by default
            const { container } = renderWithTheme(<Pill>Tag</Pill>);
            const root = container.querySelector(".mantine-Pill-root");

            expect(getCssVar(root, "--pill-height")).toBe("16px");
            expect(getCssVar(root, "--pill-fz")).toBe("10px");
        });
    });

    describe("Avatar (defaults to compact)", () => {
        it("has correct CSS variables on root by default", () => {
            // After refactor, compact styling is applied by default
            const { container } = renderWithTheme(<Avatar>AB</Avatar>);
            const root = container.querySelector(".mantine-Avatar-root");

            expect(getCssVar(root, "--avatar-size")).toBe("24px");
        });
    });

    describe("ThemeIcon (defaults to compact)", () => {
        it("has correct CSS variables on root by default", () => {
            // After refactor, compact styling is applied by default
            const { container } = renderWithTheme(
                <ThemeIcon>
                    <IconPlaceholder />
                </ThemeIcon>
            );
            const root = container.querySelector(".mantine-ThemeIcon-root");

            expect(getCssVar(root, "--ti-size")).toBe("24px");
        });
    });

    describe("Indicator (defaults to compact)", () => {
        it("has correct CSS variables on root by default", () => {
            // After refactor, compact styling is applied by default
            const { container } = renderWithTheme(
                <Indicator>
                    <div>Content</div>
                </Indicator>
            );
            const root = container.querySelector(".mantine-Indicator-root");

            expect(getCssVar(root, "--indicator-size")).toBe("8px");
        });
    });

    describe("Kbd (defaults to compact)", () => {
        it("has correct CSS variables on root by default", () => {
            // After refactor, compact styling is applied by default
            const { container } = renderWithTheme(<Kbd>Ctrl</Kbd>);
            const root = container.querySelector(".mantine-Kbd-root");

            expect(getCssVar(root, "--kbd-fz")).toBe("10px");
            expect(getCssVar(root, "--kbd-padding")).toBe("2px 4px");
        });
    });
});

/**
 * Feedback Component Baseline Verification Tests
 *
 * Tests CSS variables set by theme extensions:
 * - Loader: --loader-size: 18px
 * - Progress: --progress-size: 4px
 * - RingProgress: Uses numeric size prop (no CSS var)
 */
describe("Feedback Component CSS Baseline Verification", () => {
    describe("Loader with default size (sm)", () => {
        it("has correct CSS variables on root", () => {
            const { container } = renderWithTheme(<Loader />);
            const root = container.querySelector(".mantine-Loader-root");

            expect(getCssVar(root, "--loader-size")).toBe("18px");
        });
    });

    describe("Progress with default size (sm)", () => {
        it("has correct CSS variables on root", () => {
            const { container } = renderWithTheme(<Progress value={50} />);
            const root = container.querySelector(".mantine-Progress-root");

            expect(getCssVar(root, "--progress-size")).toBe("4px");
        });
    });

    describe("RingProgress", () => {
        it("renders with numeric size prop (no CSS var)", () => {
            // RingProgress uses numeric size directly, not CSS vars
            const { container } = renderWithTheme(
                <RingProgress size={48} sections={[{ value: 50, color: "blue" }]} />
            );
            const root = container.querySelector(".mantine-RingProgress-root");

            expect(root).toBeTruthy();
        });
    });
});

/**
 * Navigation Component Baseline Verification Tests
 *
 * Tests CSS variables set by theme extensions:
 * - Burger: --burger-size: 18px, --burger-line-size: 2px
 * - Pagination: --pagination-control-size: 24px, --pagination-control-fz: 11px
 * - Stepper: --stepper-icon-size: 24px, --stepper-fz: 11px, --stepper-spacing: 8px
 * - Anchor: Uses styles (fontSize: 11) not CSS vars
 */
describe("Navigation Component CSS Baseline Verification", () => {
    describe("Burger with default size (sm)", () => {
        it("has correct CSS variables on root", () => {
            const { container } = renderWithTheme(<Burger opened={false} />);
            const root = container.querySelector(".mantine-Burger-root");

            expect(getCssVar(root, "--burger-size")).toBe("18px");
            expect(getCssVar(root, "--burger-line-size")).toBe("2px");
        });
    });

    describe("Pagination with default size (sm)", () => {
        it("has correct CSS variables on root", () => {
            const { container } = renderWithTheme(<Pagination total={10} />);
            const root = container.querySelector(".mantine-Pagination-root");

            expect(getCssVar(root, "--pagination-control-size")).toBe("24px");
            expect(getCssVar(root, "--pagination-control-fz")).toBe("11px");
        });
    });

    describe("Stepper with default size (sm)", () => {
        it("has correct CSS variables on root", () => {
            const { container } = renderWithTheme(
                <Stepper active={1}>
                    <Stepper.Step label="Step 1" description="First" />
                    <Stepper.Step label="Step 2" description="Second" />
                </Stepper>
            );
            const root = container.querySelector(".mantine-Stepper-root");

            expect(getCssVar(root, "--stepper-icon-size")).toBe("24px");
            expect(getCssVar(root, "--stepper-fz")).toBe("11px");
            expect(getCssVar(root, "--stepper-spacing")).toBe("8px");
        });
    });

    describe("Anchor with default size (sm)", () => {
        it("renders with default size (uses styles, not CSS vars)", () => {
            // Anchor uses styles function for fontSize, not CSS vars
            const { container } = renderWithTheme(<Anchor href="#">Link</Anchor>);
            const root = container.querySelector(".mantine-Anchor-root");

            expect(root).toBeTruthy();
        });
    });
});
