// Copies compact-mantine's real global CSS (tokens, AA block, primitives) out of the PR #409
// worktree's build into kit/cm.css, with the bundled Inter face as a local file.
// Run: node kit/build-cm-css.mjs   (after `npm run build` in the compact-mantine worktree)
import { copyFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const cm = "/home/apowers/Projects/graphty-monorepo/.worktrees/compact-mantine-figma/compact-mantine";
const { compactGlobalCss } = await import(join(cm, "dist/index.js"));

// The app always builds its theme with highContrast (visual-language.md A8).
let css = compactGlobalCss({ highContrast: true });
css = css.replace(/url\("data:font\/woff2;base64,[^"]+"\)/, 'url("fonts/inter-latin-wght-normal.woff2")');
copyFileSync(join(cm, "src/fonts/inter-latin-wght-normal.woff2"), join(here, "fonts/inter-latin-wght-normal.woff2"));
copyFileSync(join(cm, "src/fonts/LICENSE-Inter.txt"), join(here, "fonts/LICENSE-Inter.txt"));
writeFileSync(
    join(here, "cm.css"),
    `/* THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT kit/build-cm-css.mjs
   (or compact-mantine's src/theme on the PR #409 worktree) and re-run it. */\n${css}`,
);
console.log(`cm.css: ${css.length} chars`);
