// Builds kit/icons.svg, a sprite of lucide icons (ISC), from the monorepo's installed lucide-react.
// Add a name to NAMES and re-run: node kit/build-icons.mjs
// Use: <svg class="k-i"><use href="../kit/icons.svg#search"/></svg>
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pnpm = join(here, "../../../../node_modules/.pnpm");
const pkg = readdirSync(pnpm).find((d) => d.startsWith("lucide-react@"));
const dir = join(pnpm, pkg, "node_modules/lucide-react/dist/esm/icons");

export const NAMES = `menu search plus minus x check chevron-down chevron-right chevron-left chevron-up
eye eye-off lock lock-open ellipsis ellipsis-vertical settings sliders-horizontal
mouse-pointer-2 lasso hand route sticky-note zap box square circle-help play pause skip-forward
download upload share folder-open file file-plus table chart-column chart-scatter sparkles
message-square flask-conical layers network circle-dot spline group waypoints palette funnel
history undo-2 redo-2 info triangle-alert circle-x circle-check copy trash-2 grip-vertical
maximize-2 minimize-2 zoom-in zoom-out scan crosshair target pin bookmark camera keyboard sun
moon arrow-up-down arrow-right arrow-left link database plug bot sigma hash type calendar clock
loader-circle refresh-cw git-compare-arrows split list-filter scissors tag users user building-2
dna credit-card shield-alert book-open graduation-cap pencil text-cursor-input
panel-left panel-right panel-bottom move gauge cpu unlink bookmark-plus snowflake`.split(/\s+/);

const attrs = (o) =>
    Object.entries(o)
        .filter(([k]) => k !== "key")
        .map(([k, v]) => `${k}="${v}"`)
        .join(" ");

const symbols = [];
const missing = [];
for (const name of NAMES) {
    let src;
    try {
        src = readFileSync(join(dir, `${name}.js`), "utf8");
    } catch {
        missing.push(name);
        continue;
    }
    let m = src.match(/const __iconNode = (\[[\s\S]*?\]);\n/);
    // An alias file re-exports another icon: follow it once.
    const alias = !m && src.match(/from '\.\/([a-z0-9-]+)\.js'/);
    if (alias) m = readFileSync(join(dir, `${alias[1]}.js`), "utf8").match(/const __iconNode = (\[[\s\S]*?\]);\n/);
    if (!m) {
        missing.push(name);
        continue;
    }
    const arr = m[1];
    const nodes = Function(`return ${arr}`)();
    const body = nodes.map(([tag, a]) => `<${tag} ${attrs(a)}/>`).join("");
    symbols.push(`<symbol id="${name}" viewBox="0 0 24 24">${body}</symbol>`);
}
// Stroke is set on the <svg> that uses the symbol (kit.css .k-i), so currentColor and the
// 1 CSS px absolute stroke (visual-language.md A7) apply.
writeFileSync(
    join(here, "icons.svg"),
    `<!-- THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT kit/build-icons.mjs. Icons: lucide (ISC). -->\n<svg xmlns="http://www.w3.org/2000/svg">\n${symbols.join("\n")}\n</svg>\n`,
);
console.log(`icons.svg: ${symbols.length} icons${missing.length ? `; missing: ${missing.join(" ")}` : ""}`);
