export const SHAPE_CONSTANTS = {
    GOLDEN_RATIO: 1.618,
    DEFAULT_NODE_SIZE: 1,
    TORUSKNOT_RADIUS_MULTIPLIER: 0.3,
    TORUSKNOT_TUBE_MULTIPLIER: 0.2,
    TORUSKNOT_RADIAL_SEGMENTS: 128,
    ICOSPHERE_RADIUS_MULTIPLIER: 0.75,
} as const;

export enum PolyhedronType {
    TETRAHEDRON = 0,
    OCTAHEDRON = 1,
    DODECAHEDRON = 2,
    ICOSAHEDRON = 3,
    RHOMBICUBOCTAHEDRON = 4,
    TRIANGULAR_PRISM = 5,
    PENTAGONAL_PRISM = 6,
    HEXAGONAL_PRISM = 7,
    SQUARE_PYRAMID = 8,
    PENTAGONAL_PYRAMID = 9,
    TRIANGULAR_DIPYRAMID = 10,
    PENTAGONAL_DIPYRAMID = 11,
    ELONGATED_SQUARE_DIPYRAMID = 12,
    ELONGATED_PENTAGONAL_DIPYRAMID = 13,
    ELONGATED_PENTAGONAL_CUPOLA = 14,
}

export const EDGE_CONSTANTS = {
    DEFAULT_LINE_WIDTH: 8.0,
    DEFAULT_LINE_COLOR: "#FFFFFF",
    DEFAULT_ARROW_WIDTH: 1.25,
    DEFAULT_ARROW_LENGTH: 0.5,
    ARROW_CAP_WIDTH_MULTIPLIER: 20,
    ARROW_CAP_WIDTH_MINIMUM: 4,
    ARROW_CAP_LENGTH_MINIMUM: 0.5,
    MOVING_LINE_BASE_COLOR: "#D3D3D3",
    MOVING_LINE_DEFAULT_COLOR: "#FF0000",
    MOVING_TEXTURE_U_SCALE: 5,
    MOVING_TEXTURE_ANIMATION_SPEED: 0.04,
    // Opacity defaults
    DEFAULT_ARROW_OPACITY: 1.0,
    DEFAULT_LINE_OPACITY: 1.0,
    // Arrow shape dimensions
    ARROW_DOT_RADIUS_MULTIPLIER: 0.15,
    ARROW_SPHERE_DOT_DIAMETER_RATIO: 0.25, // sphere-dot diameter is 1/4 of standard arrow length
    ARROW_DIAMOND_ASPECT_RATIO: 1.5,
    ARROW_BOX_ASPECT_RATIO: 1.0,
    // Hollow and line-based arrow dimensions
    ARROW_CROW_FORK_ANGLE: 30, // degrees
    ARROW_VEE_ANGLE: 60, // degrees
    ARROW_HALF_OPEN_RATIO: 0.5,
    // Line pattern parameters (multipliers relative to line width)
    DASH_LENGTH_MULTIPLIER: 3.0, // Dash length = 3x line width
    DASH_GAP_MULTIPLIER: 2.0, // Gap length = 2x line width
    SINEWAVE_AMPLITUDE_MULTIPLIER: 2,
    SINEWAVE_FREQUENCY_DEFAULT: 0.5,
    ZIGZAG_AMPLITUDE_MULTIPLIER: 2,
    ZIGZAG_FREQUENCY_DEFAULT: 1.0,
    // Bezier curve parameters
    BEZIER_CONTROL_POINT_OFFSET: 0.3,
    BEZIER_POINT_DENSITY: 8, // Lowered from 20 to reduce segment count and improve rendering
} as const;
