export const SHAPE_CONSTANTS = {
    GOLDEN_RATIO: 1.618,
    DEFAULT_NODE_SIZE: 1,
    TORUSKNOT_RADIUS_MULTIPLIER: 0.3,
    TORUSKNOT_TUBE_MULTIPLIER: 0.2,
    TORUSKNOT_RADIAL_SEGMENTS: 128,
    ICOSPHERE_RADIUS_MULTIPLIER: 0.75,
} as const;

export enum PolyhedronType {
    TETRAHEDRON = 0,
    OCTAHEDRON = 1,
    DODECAHEDRON = 2,
    ICOSAHEDRON = 3,
    RHOMBICUBOCTAHEDRON = 4,
    TRIANGULAR_PRISM = 5,
    PENTAGONAL_PRISM = 6,
    HEXAGONAL_PRISM = 7,
    SQUARE_PYRAMID = 8,
    PENTAGONAL_PYRAMID = 9,
    TRIANGULAR_DIPYRAMID = 10,
    PENTAGONAL_DIPYRAMID = 11,
    ELONGATED_SQUARE_DIPYRAMID = 12,
    ELONGATED_PENTAGONAL_DIPYRAMID = 13,
    ELONGATED_PENTAGONAL_CUPOLA = 14,
}

export const EDGE_CONSTANTS = {
    DEFAULT_LINE_WIDTH: 0.25,
    DEFAULT_LINE_COLOR: "#FFFFFF",
    ARROW_CAP_WIDTH_MULTIPLIER: 20,
    ARROW_CAP_WIDTH_MINIMUM: 4,
    ARROW_CAP_LENGTH_MINIMUM: 0.5,
    MOVING_LINE_BASE_COLOR: "#D3D3D3",
    MOVING_LINE_DEFAULT_COLOR: "#FF0000",
    MOVING_TEXTURE_U_SCALE: 5,
    MOVING_TEXTURE_ANIMATION_SPEED: 0.04,
} as const;
