/**
 * @file `@graphty/graphty-element/jsx`: `<graphty-element>` typed for JSX.
 *
 * THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE. INSTEAD EDIT scripts/generate-jsx-types.ts
 * (`npm run build` rewrites it from the custom elements manifest).
 *
 * Nothing is declared until a program opts in, with one line anywhere in it:
 *
 * ```ts
 * import type {} from "@graphty/graphty-element/jsx";
 * ```
 *
 * or with `"types": ["@graphty/graphty-element/jsx"]` in tsconfig.json. This entry point has no
 * JavaScript: it carries types only. Importing the element never applies it.
 *
 * The declaration is for React 19, which assigns a prop whose name is a property of the element as
 * that property and binds an `on<event-name>` prop as a listener for that DOM event. Another JSX
 * framework can declare the tag in its own namespace with {@link GraphtyElementJSXProps}.
 */

import type * as ReactTypes from "react";

import type { Graphty, GraphtyElementEventMap } from "./index";
import type { EventOfType } from "./src/events";

/**
 * Every property, attribute and event listener `<graphty-element>` accepts in JSX, besides the
 * ordinary HTML attributes.
 */
export interface GraphtyElementJSXProps {
    /**
     * Replaces the graph's nodes with these, as one undoable step: a node the array names again
     * keeps its row and its edges, and one it no longer names goes, with its edges.
     */
    nodeData?: Graphty["nodeData"];
    /**
     * Replaces the graph's edges with these, as one undoable step.
     */
    edgeData?: Graphty["edgeData"];
    /**
     * Sets the data source type. Loads the graph from it, replacing what the graph held, once the
     * configuration is set too.
     */
    dataSource?: Graphty["dataSource"];
    /**
     * Sets the data source configuration. Loads the graph from it, replacing what the graph
     * held, once the type is set too.
     */
    dataSourceConfig?: Graphty["dataSourceConfig"];
    /**
     * Sets the JMESPath for node ID extraction. Updates graph configuration.
     */
    nodeIdPath?: Graphty["nodeIdPath"];
    /**
     * Sets the JMESPath for edge source ID extraction. Updates graph configuration.
     */
    edgeSrcIdPath?: Graphty["edgeSrcIdPath"];
    /**
     * Sets the JMESPath for edge destination ID extraction. Updates graph configuration.
     */
    edgeDstIdPath?: Graphty["edgeDstIdPath"];
    /**
     * Sets the JMESPath for edge identity. Updates graph configuration.
     */
    edgeIdPath?: Graphty["edgeIdPath"];
    /**
     * Sets the repeat policy. Updates graph configuration.
     */
    repeatedEdges?: Graphty["repeatedEdges"];
    /**
     * Sets the JMESPath for a node's display name. Updates graph configuration.
     */
    nodeLabelPath?: Graphty["nodeLabelPath"];
    /**
     * Sets the JMESPath for an edge's weight. Updates graph configuration.
     */
    edgeWeightPath?: Graphty["edgeWeightPath"];
    /**
     * Sets the record-units-to-scene-units multiplier. Updates graph configuration.
     */
    positionScale?: Graphty["positionScale"];
    /**
     * Sets whether the graph is read as directed. Updates graph configuration.
     */
    directed?: Graphty["directed"];
    /**
     * Sets the layout algorithm: one undoable step, which undo takes back to the layout, the
     * engine and the options before it. Assigned with `layoutConfig` in the same tick, the two are
     * one step.
     */
    layout?: Graphty["layout"];
    /**
     * Sets layout-specific configuration: the layout is drawn again with it, as one undoable step.
     */
    layoutConfig?: Graphty["layoutConfig"];
    /**
     * Sets what the layout runs over, and restarts the running layout over it. A value that is
     * not a scope is reported and dropped, never thrown: this setter is reached from
     * `attributeChangedCallback`, where a throw would reach nobody.
     */
    layoutScope?: Graphty["layoutScope"];
    /**
     * Sets how the element drives the layout.
     *
     * A value the schema refuses is reported and dropped rather than thrown, on the same terms
     * as `background` and `acceleration`.
     */
    layoutBehavior?: Graphty["layoutBehavior"];
    /**
     * Switches label decluttering on or off.
     */
    labelDeclutter?: Graphty["labelDeclutter"];
    /**
     * Sets what a selected node looks like.
     */
    selectionStyle?: Graphty["selectionStyle"];
    /**
     * Sets which algorithms run once data has finished loading.
     */
    algorithmsOnLoad?: Graphty["algorithmsOnLoad"];
    /**
     * Sets the view mode. Switching between 2D and 3D is one undoable step; entering VR or AR is
     * not a step, and from 2D it switches to 3D first in the same step.
     */
    viewMode?: Graphty["viewMode"];
    /**
     * Sets 2D mode (deprecated). Converts boolean to viewMode internally.
     */
    layout2d?: Graphty["layout2d"];
    /**
     * Sets the graph background. Applies it to the scene immediately.
     *
     * A value the schema refuses is REPORTED AND DROPPED rather than thrown, on the same terms
     * as `acceleration`: this setter is reached from `attributeChangedCallback`, and a throw
     * there escapes as an unhandled rejection that reaches nobody, leaving the page with an
     * element that never rendered. A wrong colour in markup must not take the graph down.
     */
    background?: Graphty["background"];
    /**
     * Sets the starting camera distance.
     */
    startingCameraDistance?: Graphty["startingCameraDistance"];
    /**
     * Switches the camera's own framing on or off.
     */
    autoFrame?: Graphty["autoFrame"];
    /**
     * Sets whether to run algorithms when a style template loads. Updates graph configuration.
     */
    runAlgorithmsOnLoad?: Graphty["runAlgorithmsOnLoad"];
    /**
     * Turns the element's own undo keys on or off.
     */
    historyKeys?: Graphty["historyKeys"];
    /**
     * Sets detailed profiling mode. Enables hierarchical timing and advanced stats collection.
     */
    enableDetailedProfiling?: Graphty["enableDetailedProfiling"];
    /**
     * Sets XR configuration. Updates VR/AR settings and UI options.
     */
    xr?: Graphty["xr"];
    /**
     * Sets the acceleration policy and applies it immediately.
     *
     * An unrecognised value is reported and then ignored, leaving the previous policy in
     * force. It is not thrown. Lit drives this setter from `attributeChangedCallback`, so a
     * throw here would abort attribute processing and leave the element unrendered -- a typo
     * in markup would take the whole graph down. HTML has never behaved that way about an
     * attribute value, and an embedded component must not be the first thing that does.
     *
     * The report is deliberately loud, because the quiet failure is the dangerous one: a page
     * that meant `required` and wrote `requried` would otherwise run on the CPU and look
     * healthy.
     */
    acceleration?: Graphty["acceleration"];
    /**
     * Sets the renderer the element opens when it is first drawn.
     *
     * An unrecognised value, or a change once the element is drawing, is reported and ignored
     * rather than thrown, for the reason given on `acceleration`: Lit drives this setter from
     * `attributeChangedCallback`, and a throw there would leave the element unrendered.
     */
    renderer?: Graphty["renderer"];
    /**
     * Sets the threshold and applies it immediately.
     *
     * A value that is not a whole number of 0 or more is reported and then ignored, leaving the
     * previous threshold in force, for the reason the `acceleration` setter states: Lit drives
     * this from `attributeChangedCallback`, and a throw there would leave the element unrendered.
     */
    accelerationMinNodes?: Graphty["accelerationMinNodes"];
    /**
     * Replaces the graph's nodes with these, as one undoable step: a node the array names again
     * keeps its row and its edges, and one it no longer names goes, with its edges.
     */
    "node-data"?: string;
    /**
     * Replaces the graph's edges with these, as one undoable step.
     */
    "edge-data"?: string;
    /**
     * Sets the data source type. Loads the graph from it, replacing what the graph held, once the
     * configuration is set too.
     */
    "data-source"?: string;
    /**
     * Sets the data source configuration. Loads the graph from it, replacing what the graph
     * held, once the type is set too.
     */
    "data-source-config"?: string;
    /**
     * Sets the JMESPath for node ID extraction. Updates graph configuration.
     */
    "node-id-path"?: string;
    /**
     * Sets the JMESPath for edge source ID extraction. Updates graph configuration.
     */
    "edge-src-id-path"?: string;
    /**
     * Sets the JMESPath for edge destination ID extraction. Updates graph configuration.
     */
    "edge-dst-id-path"?: string;
    /**
     * Sets the JMESPath for edge identity. Updates graph configuration.
     */
    "edge-id-path"?: string;
    /**
     * Sets the repeat policy. Updates graph configuration.
     */
    "repeated-edges"?: string;
    /**
     * Sets the JMESPath for a node's display name. Updates graph configuration.
     */
    "node-label-path"?: string;
    /**
     * Sets the JMESPath for an edge's weight. Updates graph configuration.
     */
    "edge-weight-path"?: string;
    /**
     * Sets the record-units-to-scene-units multiplier. Updates graph configuration.
     */
    "position-scale"?: string;
    /**
     * Sets layout-specific configuration: the layout is drawn again with it, as one undoable step.
     */
    "layout-config"?: string;
    /**
     * Sets what the layout runs over, and restarts the running layout over it. A value that is
     * not a scope is reported and dropped, never thrown: this setter is reached from
     * `attributeChangedCallback`, where a throw would reach nobody.
     */
    "layout-scope"?: string;
    /**
     * Switches label decluttering on or off.
     */
    "label-declutter"?: boolean;
    /**
     * Sets the view mode. Switching between 2D and 3D is one undoable step; entering VR or AR is
     * not a step, and from 2D it switches to 3D first in the same step.
     */
    "view-mode"?: string;
    /**
     * Sets 2D mode (deprecated). Converts boolean to viewMode internally.
     */
    "layout-2d"?: boolean;
    /**
     * Sets the starting camera distance.
     */
    "starting-camera-distance"?: string;
    /**
     * Switches the camera's own framing on or off.
     */
    "auto-frame"?: boolean;
    /**
     * Sets whether to run algorithms when a style template loads. Updates graph configuration.
     */
    "run-algorithms-on-load"?: boolean;
    /**
     * Turns the element's own undo keys on or off.
     */
    "history-keys"?: boolean;
    /**
     * Sets detailed profiling mode. Enables hierarchical timing and advanced stats collection.
     */
    "enable-detailed-profiling"?: boolean;
    /**
     * Sets the threshold and applies it immediately.
     *
     * A value that is not a whole number of 0 or more is reported and then ignored, leaving the
     * previous threshold in force, for the reason the `acceleration` setter states: Lit drives
     * this from `attributeChangedCallback`, and a throw there would leave the element unrendered.
     */
    "acceleration-min-nodes"?: string;
    /**
     * Emitted when an AI command is cancelled
     */
    "onai-command-cancelled"?: (event: CustomEvent<EventOfType<"ai-command-cancelled">>) => void;
    /**
     * Emitted when an AI command completes successfully
     */
    "onai-command-complete"?: (event: CustomEvent<EventOfType<"ai-command-complete">>) => void;
    /**
     * Emitted when an AI command encounters an error
     */
    "onai-command-error"?: (event: CustomEvent<EventOfType<"ai-command-error">>) => void;
    /**
     * Emitted when an AI command starts processing
     */
    "onai-command-start"?: (event: CustomEvent<EventOfType<"ai-command-start">>) => void;
    /**
     * Main event for UI binding - single source of truth for AI status
     */
    "onai-status-change"?: (event: CustomEvent<EventOfType<"ai-status-change">>) => void;
    /**
     * Emitted during streaming when text chunks arrive (throttled)
     */
    "onai-stream-chunk"?: (event: CustomEvent<EventOfType<"ai-stream-chunk">>) => void;
    /**
     * Emitted when the LLM makes a tool call
     */
    "onai-stream-tool-call"?: (event: CustomEvent<EventOfType<"ai-stream-tool-call">>) => void;
    /**
     * Emitted when a tool call completes
     */
    "onai-stream-tool-result"?: (event: CustomEvent<EventOfType<"ai-stream-tool-result">>) => void;
    /**
     * Emitted when voice input ends
     */
    "onai-voice-end"?: (event: CustomEvent<EventOfType<"ai-voice-end">>) => void;
    /**
     * Emitted when voice input starts
     */
    "onai-voice-start"?: (event: CustomEvent<EventOfType<"ai-voice-start">>) => void;
    /**
     * Emitted when voice transcript is available
     */
    "onai-voice-transcript"?: (event: CustomEvent<EventOfType<"ai-voice-transcript">>) => void;
    "onanimation-cancelled"?: (event: CustomEvent<EventOfType<"animation-cancelled">>) => void;
    "onanimation-progress"?: (event: CustomEvent<EventOfType<"animation-progress">>) => void;
    "oncamera-state-changed"?: (event: CustomEvent<EventOfType<"camera-state-changed">>) => void;
    "ondata-added"?: (event: CustomEvent<EventOfType<"data-added">>) => void;
    /**
     * Emitted once every time the graph's data is cleared -- by `clearData()`, and by a load that
     */
    "ondata-cleared"?: (event: CustomEvent<EventOfType<"data-cleared">>) => void;
    "ondata-loaded"?: (event: CustomEvent<EventOfType<"data-loaded">>) => void;
    "ondata-loading-complete"?: (event: CustomEvent<EventOfType<"data-loading-complete">>) => void;
    "ondata-loading-error"?: (event: CustomEvent<EventOfType<"data-loading-error">>) => void;
    "ondata-loading-error-summary"?: (event: CustomEvent<EventOfType<"data-loading-error-summary">>) => void;
    "ondata-loading-progress"?: (event: CustomEvent<EventOfType<"data-loading-progress">>) => void;
    /**
     * Emitted once per `removeNodes` call, naming everything that went.
     */
    "onelements-removed"?: (event: CustomEvent<EventOfType<"elements-removed">>) => void;
    onerror?: (event: CustomEvent<EventOfType<"error">>) => void;
    "ongraph-frame-stable"?: (event: CustomEvent<EventOfType<"graph-frame-stable">>) => void;
    "ongraph-settled"?: (event: CustomEvent<EventOfType<"graph-settled">>) => void;
    "ongraphty-capabilities-change"?: (event: GraphtyElementEventMap["graphty-capabilities-change"]) => void;
    "ongraphty-history-change"?: (event: GraphtyElementEventMap["graphty-history-change"]) => void;
    "ongraphty-label-change"?: (event: GraphtyElementEventMap["graphty-label-change"]) => void;
    "ongraphty-node-click"?: (event: GraphtyElementEventMap["graphty-node-click"]) => void;
    "ongraphty-node-drag-end"?: (event: GraphtyElementEventMap["graphty-node-drag-end"]) => void;
    "ongraphty-node-drag-start"?: (event: GraphtyElementEventMap["graphty-node-drag-start"]) => void;
    "ongraphty-node-hover"?: (event: GraphtyElementEventMap["graphty-node-hover"]) => void;
    "ongraphty-note-change"?: (event: GraphtyElementEventMap["graphty-note-change"]) => void;
    "ongraphty-progress-change"?: (event: GraphtyElementEventMap["graphty-progress-change"]) => void;
    "ongraphty-project-status"?: (event: GraphtyElementEventMap["graphty-project-status"]) => void;
    "ongraphty-run-change"?: (event: GraphtyElementEventMap["graphty-run-change"]) => void;
    "ongraphty-selection-change"?: (event: GraphtyElementEventMap["graphty-selection-change"]) => void;
    "ongraphty-visibility-change"?: (event: GraphtyElementEventMap["graphty-visibility-change"]) => void;
    "onlayout-initialized"?: (event: CustomEvent<EventOfType<"layout-initialized">>) => void;
    "onlayout-progress"?: (event: CustomEvent<EventOfType<"layout-progress">>) => void;
    "onlifecycle-disposed"?: (event: CustomEvent<EventOfType<"lifecycle-disposed">>) => void;
    "onlifecycle-initialized"?: (event: CustomEvent<EventOfType<"lifecycle-initialized">>) => void;
    "onmanager-initialized"?: (event: CustomEvent<EventOfType<"manager-initialized">>) => void;
    "onoperation-batch-complete"?: (event: CustomEvent<EventOfType<"operation-batch-complete">>) => void;
    "onoperation-complete"?: (event: CustomEvent<EventOfType<"operation-complete">>) => void;
    "onoperation-obsoleted"?: (event: CustomEvent<EventOfType<"operation-obsoleted">>) => void;
    "onoperation-progress"?: (event: CustomEvent<EventOfType<"operation-progress">>) => void;
    "onoperation-queue-active"?: (event: CustomEvent<EventOfType<"operation-queue-active">>) => void;
    "onoperation-queue-idle"?: (event: CustomEvent<EventOfType<"operation-queue-idle">>) => void;
    "onoperation-start"?: (event: CustomEvent<EventOfType<"operation-start">>) => void;
    "onrender-initialized"?: (event: CustomEvent<EventOfType<"render-initialized">>) => void;
    "onscreenshot-enhancing"?: (event: CustomEvent<EventOfType<"screenshot-enhancing">>) => void;
    "onscreenshot-ready"?: (event: CustomEvent<EventOfType<"screenshot-ready">>) => void;
    "onselection-changed"?: (event: CustomEvent<EventOfType<"selection-changed">>) => void;
    "onskybox-loaded"?: (event: CustomEvent<EventOfType<"skybox-loaded">>) => void;
    /**
     * Emitted after the style stack changed and the graph was repainted for it.
     */
    "onstyle-changed"?: (event: CustomEvent<EventOfType<"style-changed">>) => void;
    "onzoom-to-fit-complete"?: (event: CustomEvent<EventOfType<"zoom-to-fit-complete">>) => void;
}

// Named through an alias: inside the augmentation, a bare DetailedHTMLProps is React's own
// module-scope name, which the declaration emit cannot write.
declare module "react" {
    namespace JSX {
        interface IntrinsicElements {
            "graphty-element": ReactTypes.DetailedHTMLProps<ReactTypes.HTMLAttributes<Graphty>, Graphty> &
                GraphtyElementJSXProps;
        }
    }
}
